#Region "CommonUIData"
Public Class CommonUIData

#Region "Declaration Part.."
    'Data Tables..
    Public Const _ALERT As String = "ALERT"
    Public Const _ACTIVITY As String = "ACTIVITY"
    Public Const _CHOOSE_TABLE As String = "CHOOSE_TABLE"
    Public Const _DEPOT As String = "DEPOT"
    Public Const _ENUM As String = "ENUM"
    Public Const _MAX_SNO As String = "MAX_SNO"
    Public Const _PROCESS As String = "PROCESS"
    Public Const _ROLE As String = "ROLE"
    Public Const _ROLE_RIGHT As String = "ROLE_RIGHT"
    Public Const _UNIT As String = "UNIT"
    Public Const _USER_DETAIL As String = "USER_DETAIL"
    Public Const _USER_LOG As String = "USER_LOG"
    Public Const _V_USER_DETAIL As String = "V_USER_DETAIL"
    Public Const _REPORT_PARAMETER As String = "REPORT_PARAMETER"
    Public Const _V_GATEIN As String = "V_GATEIN"
    Public Const _V_GATEOUT As String = "V_GATEOUT"
    Public Const _V_TRACKING As String = "V_TRACKING"
    Public Const _DOCUMENT As String = "DOCUMENT"
    Public Const _DOCUMENT_TEMPLATE As String = "DOCUMENT_TEMPLATE"
    Public Const _V_REPAIR_ESTIMATE As String = "V_REPAIR_ESTIMATE"
    Public Const _V_REPAIR_ESTIMATE_DETAIL As String = "V_REPAIR_ESTIMATE_DETAIL"
    Public Const _ESTIMATION_PROCESS As String = "ESTIMATION_PROCESS"
    Public Const _V_INVENTORY As String = "V_INVENTORY"
    Public Const _V_RPT_REPAIRCOMPLETED As String = "V_RPT_REPAIRCOMPLETED"
    Public Const _V_RPT_AVAILABLEUNITS As String = "V_RPT_AVAILABLEUNITS"
    Public Const _REPAIR_SUMMARY_DETAIL As String = "REPAIR_SUMMARY_DETAIL"
    Public Const _V_RPT_PENDINGINVOICE As String = "V_RPT_PENDINGINVOICE"
    Public Const _TRACKING As String = "TRACKING"
    Public Const _EQUIPMENT_STATUS As String = "EQUIPMENT_STATUS"
    Public Const _EQUIPMENT_TYPE As String = "EQUIPMENT_TYPE"
    Public Const _EQUIPMENT_CODE As String = "EQUIPMENT_CODE"
    Public Const _WF_ACTIVITY As String = "WF_ACTIVITY"
    Public Const _V_ACTIVITY_STATUS As String = "V_ACTIVITY_STATUS"
    Public Const _SERVICE_PARTNER As String = "SERVICE_PARTNER"
    Public Const _V_SERVICE_PARTNER As String = "V_SERVICE_PARTNER"
    Public Const _ATTACHMENT As String = "ATTACHMENT"
    Public Const _HANDLING_CHARGE As String = "HANDLING_CHARGE"
    Public Const _STORAGE_CHARGE As String = "STORAGE_CHARGE"
    Public Const _INVOICE_HISTORY As String = "INVOICE_HISTORY"
    Public Const _CLEANING_CHARGE As String = "CLEANING_CHARGE"
    Public Const _HEATING_CHARGE As String = "HEATING_CHARGE"
    Public Const _REPAIR_CHARGE As String = "REPAIR_CHARGE"
    Public Const _MISCELLANEOUS_INVOICE As String = "MISCELLANEOUS_INVOICE"
    Public Const _V_HANDLING_CHARGE As String = "V_HANDLING_CHARGE"
    Public Const _V_STORAGE_CHARGE As String = "V_STORAGE_CHARGE"
    Public Const _HANDLING_STORAGE_INVOICE As String = "HANDLING_STORAGE_INVOICE"
    Public Const _CUSTOMER As String = "CUSTOMER"
    Public Const _V_CUSTOMER As String = "V_CUSTOMER"
    Public Const _V_BANK_DETAIL As String = "V_BANK_DETAIL"
    Public Const _V_INVOICING_PARTY As String = "V_INVOICING_PARTY"
    Public Const _V_CUSTOMER_CHARGE_DETAIL As String = "V_CUSTOMER_CHARGE_DETAIL"
    Public Const _V_REPAIR_CHARGE As String = "V_REPAIR_CHARGE"
    Public Const _PENDING_INVOICE As String = "PENDING_INVOICE"
    Public Const _FOREIGN_BANK_DETAIL As String = "FOREIGN_BANK_DETAIL"
    Public Const _V_CLEANING_CHARGE As String = "V_CLEANING_CHARGE"
    Public Const _V_MISCELLANEOUS_INVOICE As String = "V_MISCELLANEOUS_INVOICE"
    Public Const _V_HEATING_CHARGE As String = "V_HEATING_CHARGE"
    Public Const _V_EXCHANGE_RATE As String = "V_EXCHANGE_RATE"
    Public Const _HEATING_INVOICE As String = "HEATING_INVOICE"
    Public Const _CLEANING_INVOICE As String = "CLEANING_INVOICE"
    Public Const _REPAIR_INVOICE As String = "REPAIR_INVOICE"
    Public Const _V_CLEANING As String = "V_CLEANING"
    Public Const _V_DAR_ACTIVITY_STATUS As String = "V_DAR_ACTIVITY_STATUS"
    Public Const _V_DAR_CUSTOMER_SUMMARY As String = "V_DAR_CUSTOMER_SUMMARY"
    Public Const _V_DAR_TYPE_SUMMARY As String = "V_DAR_TYPE_SUMMARY"
    Public Const _ACTIVITY_STATUS As String = "ACTIVITY_STATUS"
    Public Const _V_EQUIPMENT_ACTIVTY_DATE As String = "V_EQUIPMENT_ACTIVTY_DATE"
    Public Const _V_EQUIPMENT_ACTIVTY_TYPE As String = "V_EQUIPMENT_ACTIVTY_TYPE"
    Public Const _VM_HEATING As String = "VM_HEATING"
    Public Const _VM_TANK_TEST_DETAIL As String = "VM_TANK_TEST_DETAIL"
    Public Const _V_TRANSPORTATION_INVOICE As String = "V_TRANSPORTATION_INVOICE"
    Public Const _TRANSPORTATION_CHARGE As String = "TRANSPORTATION_CHARGE"
    Public Const _VM_TRANSPORTATION As String = "VM_TRANSPORTATION"
    Public Const _INVOICE_HISTORY_DETAIL As String = "INVOICE_HISTORY_DETAIL"
    Public Const _AUDIT_LOG As String = "AUDIT_LOG"
    Public Const _V_TRANSPORTATION_CHARGE As String = "V_TRANSPORTATION_CHARGE"
    Public Const _V_TRANSPORTATION_DETAIL_RATE As String = "V_TRANSPORTATION_DETAIL_RATE"
    Public Const _V_TRANSPORTATION_DETAIL As String = "V_TRANSPORTATION_DETAIL"
    Public Const _VM_RENATL As String = "VM_RENTAL"
    Public Const _RENTAL_CHARGE As String = "RENTAL_CHARGE"
    Public Const _V_RENTAL_CHARGE As String = "V_RENTAL_CHARGE"
    Public Const _RENTAL_INVOICE As String = "RENTAL_INVOICE"
    Public Const _VM_FINANCE_HANDLINGANDSTORAGE As String = "VM_FINANCE_HANDLINGANDSTORAGE"
    Public Const _VM_FINANCE_RENTAL_SUMMARY As String = "VM_FINANCE_RENTAL_SUMMARY"
    Public Const _V_EQUIPMENT_INFORMATION As String = "V_EQUIPMENT_INFORMATION"
    Public Const _V_EQUIPMENT_ACTIVITY_DATE_DETAIL As String = "V_EQUIPMENT_ACTIVITY_DATE_DETAIL"
    Public Const _V_CLEANING_METHOD_DETAIL As String = "V_CLEANING_METHOD_DETAIL"
    Public Const _CLEANING_TYPE As String = "CLEANING_TYPE"
    Public Const _MAX_SNO_DETAIL As String = "MAX_SNO_DETAIL"
    Public Const _INDEX_PATTERN As String = "INDEX_PATTERN"
    Public Const _V_INDEX_PATTERN_DETAIL As String = "V_INDEX_PATTERN_DETAIL"
    Public Const _V_INSPECTION_CHARGES As String = "V_INSPECTION_CHARGES"
    Public Const _INSPECTION_CHARGES As String = "INSPECTION_CHARGES"

    'Data Columns..
    Public Const MY_SBMTS_CLCNT = "MY_SBMTS_CLCNT"
    Public Const MY_SBMTS_QRY = "MY_SBMTS_QRY"
    'Table Name: ALERT
    Public Const ALRT_ID As String = "ALRT_ID"
    Public Const RPRT_TMPLT_ID As String = "RPRT_TMPLT_ID"
    Public Const ALRT_TO As String = "ALRT_TO"
    Public Const ALRT_CC As String = "ALRT_CC"
    Public Const ALRT_SBJCT_VC As String = "ALRT_SBJCT_VC"
    Public Const ALRT_BDY_VC As String = "ALRT_BDY_VC"
    Public Const FL_NAM As String = "FL_NAM"
    Public Const ALRT_RN_DT As String = "ALRT_RN_DT"
    Public Const ERRR_VC As String = "ERRR_VC"

    'Table Name: ACTIVITY
    Public Const ACTVTY_ID As String = "ACTVTY_ID"
    Public Const ACTVTY_NAM As String = "ACTVTY_NAM"
    Public Const PRCSS_ID As String = "PRCSS_ID"
    Public Const LST_QRY As String = "LST_QRY"
    Public Const LST_URL As String = "LST_URL"
    Public Const LST_TTL As String = "LST_TTL"
    Public Const LST_CLCNT As String = "LST_CLCNT"
    Public Const PG_URL As String = "PG_URL"
    Public Const PG_TTL As String = "PG_TTL"
    Public Const TBL_NAM As String = "TBL_NAM"
    Public Const ORDR_NO As String = "ORDR_NO"
    Public Const CRT_RGHT_BT As String = "CRT_RGHT_BT"
    Public Const EDT_RGHT_BT As String = "EDT_RGHT_BT"
    Public Const ACTV_BT As String = "ACTV_BT"
    Public Const MNU_TXT As String = "MNU_TXT"
    Public Const ACTVTY_RL As String = "ACTVTY_RL"
    Public Const EXCPTN_BT As String = "EXCPTN_BT"

    'Table Name: CHOOSE_TABLE
    Public Const ID As String = "ID"
    Public Const TABLENAME As String = "TABLENAME"
    Public Const HEADERNAME As String = "HEADERNAME"
    Public Const COLUMN1NAME As String = "COLUMN1NAME"
    Public Const COLUMN1CAPTION As String = "COLUMN1CAPTION"
    Public Const COLUMN1WIDTH As String = "COLUMN1WIDTH"
    Public Const COLUMN2NAME As String = "COLUMN2NAME"
    Public Const COLUMN2CAPTION As String = "COLUMN2CAPTION"
    Public Const COLUMN2WIDTH As String = "COLUMN2WIDTH"
    Public Const COLUMN3NAME As String = "COLUMN3NAME"
    Public Const COLUMN3CAPTION As String = "COLUMN3CAPTION"
    Public Const COLUMN3WIDTH As String = "COLUMN3WIDTH"
    Public Const FILTER_CONDITION As String = "FILTER_CONDITION"
    Public Const PAGEURL As String = "PAGEURL"
    Public Const MENUID As String = "MENUID"
    Public Const COLUMN4NAME As String = "COLUMN4NAME"
    Public Const COLUMN4CAPTION As String = "COLUMN4CAPTION"
    Public Const COLUMN4WIDTH As String = "COLUMN4WIDTH"
    Public Const COLUMN5NAME As String = "COLUMN5NAME"
    Public Const COLUMN5CAPTION As String = "COLUMN5CAPTION"
    Public Const COLUMN5WIDTH As String = "COLUMN5WIDTH"
    Public Const COLUMN6NAME As String = "COLUMN6NAME"
    Public Const COLUMN6CAPTION As String = "COLUMN6CAPTION"
    Public Const COLUMN6WIDTH As String = "COLUMN6WIDTH"
    Public Const ORDERBY As String = "ORDERBY"

    'Table Name: UNIT
    Public Const UNT_ID As String = "UNT_ID"
    Public Const UNT_CD As String = "UNT_CD"
    Public Const UNT_DSCRPTN_VC As String = "UNT_DSCRPTN_VC"
    Public Const CRTD_BY As String = "CRTD_BY"
    Public Const CRTD_DT As String = "CRTD_DT"



    'Table Name: Depot
    Public Const DPT_ID As String = "DPT_ID"
    Public Const DPT_CD As String = "DPT_CD"
    Public Const DPT_NAM As String = "DPT_NAM"
    Public Const CNTCT_PRSN_NAM As String = "CNTCT_PRSN_NAM"
    Public Const ADDRSS_LN1_VC As String = "ADDRSS_LN1_VC"
    Public Const ADDRSS_LN2_VC As String = "ADDRSS_LN2_VC"
    Public Const ADDRSS_LN3_VC As String = "ADDRSS_LN3_VC"
    Public Const CNTRY_ID As String = "CNTRY_ID"
    Public Const CTY_ID As String = "CTY_ID"
    Public Const ZP_CD As String = "ZP_CD"
    Public Const VT_NO As String = "VT_NO"
    Public Const PHN_NO As String = "PHN_NO"
    Public Const FX_NO As String = "FX_NO"
    Public Const CRRNCY_ID As String = "CRRNCY_ID"
    Public Const CMPNY_LG_PTH As String = "CMPNY_LG_PTH"
    Public Const MDFD_BY As String = "MDFD_BY"
    Public Const MDFD_DT As String = "MDFD_DT"

    'Table Name: ENUM
    Public Const ENM_ID As String = "ENM_ID"
    Public Const ENM_CD As String = "ENM_CD"
    Public Const ENM_DSCRPTN_VC As String = "ENM_DSCRPTN_VC"
    Public Const ENM_TYP_ID As String = "ENM_TYP_ID"
    Public Const ENM_TYP_CD As String = "ENM_TYP_CD"

    'Table Name: MAX_SNO
    Public Const TBL_NM As String = "TBL_NM"
    Public Const MX_NO As String = "MX_NO"

    'Table Name: PROCESS
    Public Const PRCSS_NAM As String = "PRCSS_NAM"
    Public Const PRNT_ID As String = "PRNT_ID"
    Public Const PRCSS_ORDR As String = "PRCSS_ORDR"

    'Table Name: ROLE
    Public Const RL_ID As String = "RL_ID"
    Public Const RL_CD As String = "RL_CD"
    Public Const RL_DSCRPTN_VC As String = "RL_DSCRPTN_VC"

    'Table Name: ROLE_RIGHT
    Public Const RL_RGHT_ID As String = "RL_RGHT_ID"
    Public Const CRT_BT As String = "CRT_BT"
    Public Const EDT_BT As String = "EDT_BT"
    Public Const VW_BT As String = "VW_BT"

    'Table Name: USER_DETAIL
    Public Const USR_ID As String = "USR_ID"
    Public Const USR_NAM As String = "USR_NAM"
    Public Const PSSWRD As String = "PSSWRD"
    Public Const FRST_NAM As String = "FRST_NAM"
    Public Const LST_NAM As String = "LST_NAM"
    Public Const EML_ID As String = "EML_ID"
    Public Const USR_TYP_ID As String = "USR_TYP_ID"
    Public Const ASSCTD_ORGNZTN_ID As String = "ASSCTD_ORGNZTN_ID"

    'Table Name: USER_LOG
    Public Const LGN_DT As String = "LGN_DT"
    Public Const LGT_DT As String = "LGT_DT"
    Public Const IP_ADDRSS As String = "IP_ADDRSS"
    Public Const SSN_ID As String = "SSN_ID"
    Public Const USR_AGNT As String = "USR_AGNT"
    Public Const BRWSR As String = "BRWSR"
    Public Const SCRN_SZ As String = "SCRN_SZ"

    'Table Name: V_USER_DETAIL
    Public Const USR_TYP_CD As String = "USR_TYP_CD"

    'Table Name: REPORT_PARAMETER
    Public Const PRMTR_ID As String = "PRMTR_ID"
    Public Const RPRT_ID As String = "RPRT_ID"
    Public Const PRMTR_NAM As String = "PRMTR_NAM"
    Public Const PRMTR_TYP As String = "PRMTR_TYP"
    Public Const PRMTR_QRY As String = "PRMTR_QRY"
    Public Const PRMTR_OPT As String = "PRMTR_OPT"
    Public Const PRMTR_DSPLY_NAM As String = "PRMTR_DSPLY_NAM"
    Public Const PRMTR_RL As String = "PRMTR_RL"
    Public Const REQ_DPT_ID As String = "REQ_DPT_ID"
    Public Const PRMTR_ORDR_CLMN As String = "PRMTR_ORDR_CLMN"
    Public Const PRMTR_ORDR_TYP As String = "PRMTR_ORDR_TYP"

    'Table Name: V_GATEIN
    Public Const GTN_BIN As String = "GTN_BIN"
    Public Const TRNSMSSN_NO As String = "TRNSMSSN_NO"
    Public Const SNT_DT As String = "SNT_DT"
    Public Const GTN_TRNSXN As String = "GTN_TRNSXN"
    Public Const AUTH_NO As String = "AUTH_NO"
    Public Const EQPMNT_NO As String = "EQPMNT_NO"
    Public Const EQPMNT_CD_ID As String = "EQPMNT_CD_ID"
    Public Const EQPMNT_CD_CD As String = "EQPMNT_CD_CD"
    Public Const GTN_CNDTN As String = "GTN_CNDTN"
    Public Const EQPMNT_TYP_ID As String = "EQPMNT_TYP_ID"
    Public Const EQPMNT_TYP_CD As String = "EQPMNT_TYP_CD"
    Public Const EIR_DT As String = "EIR_DT"
    Public Const LSS_ID As String = "LSS_ID"
    Public Const LSS_CD As String = "LSS_CD"
    Public Const RFRNC As String = "RFRNC"
    Public Const MTRL_ID As String = "MTRL_ID"
    Public Const MTRL_CD As String = "MTRL_CD"
    Public Const MNFCTR_DT As String = "MNFCTR_DT"
    Public Const WGHT As String = "WGHT"
    Public Const MSR_ID As String = "MSR_ID"
    Public Const MSR_CD As String = "MSR_CD"
    Public Const ACEP_CD As String = "ACEP_CD"
    Public Const CNTRY_CD As String = "CNTRY_CD"
    Public Const LIC_STT As String = "LIC_STT"
    Public Const LIC_REG As String = "LIC_REG"
    Public Const CSTMR_ID As String = "CSTMR_ID"
    Public Const CSTMR_CD As String = "CSTMR_CD"
    Public Const CSTMR_NAM As String = "CSTMR_NAM"
    Public Const LIC_EXPR As String = "LIC_EXPR"
    Public Const TRCKR_CD As String = "TRCKR_CD"
    Public Const LST_OH_DT As String = "LST_OH_DT"
    Public Const NT_1_VC As String = "NT_1_VC"
    Public Const NT_2_VC As String = "NT_2_VC"
    Public Const NT_3_VC As String = "NT_3_VC"
    Public Const VHCL_NO As String = "VHCL_NO"
    Public Const TRNSPRTR_CD As String = "TRNSPRTR_CD"
    Public Const LDD_STTS_CD As String = "LDD_STTS_CD"
    Public Const LST_OH_LOC As String = "LST_OH_LOC"
    Public Const SL_PRTY_1_ID As String = "SL_PRTY_1_ID"
    Public Const SL_PRTY_1_CD As String = "SL_PRTY_1_CD"
    Public Const SL_PRTY_2_ID As String = "SL_PRTY_2_ID"
    Public Const SL_PRTY_2_CD As String = "SL_PRTY_2_CD"
    Public Const SL_NMBR_1 As String = "SL_NMBR_1"
    Public Const SL_NMBR_2 As String = "SL_NMBR_2"
    Public Const SL_PRTY_3_ID As String = "SL_PRTY_3_ID"
    Public Const SL_PRTY_3_CD As String = "SL_PRTY_3_CD"
    Public Const SL_NMBR_3 As String = "SL_NMBR_3"
    Public Const RC_EST_STTS As String = "RC_EST_STTS"
    Public Const OTWRDPSS_STTS_BT As String = "OTWRDPSS_STTS_BT"
    Public Const RSRV_BKG_BT As String = "RSRV_BKG_BT"
    Public Const YRD_LOC As String = "YRD_LOC"
    Public Const EQPMNT_STTS_ID As String = "EQPMNT_STTS_ID"
    Public Const EQPMNT_STTS_CD As String = "EQPMNT_STTS_CD"
    Public Const PRT_LC_CD As String = "PRT_LC_CD"
    Public Const LOC_DNT As String = "LOC_DNT"
    Public Const VSSL_CD As String = "VSSL_CD"
    Public Const RL_RMP_LOC As String = "RL_RMP_LOC"
    Public Const RL_ID_VC As String = "RL_ID_VC"
    Public Const SHPPR_NAM As String = "SHPPR_NAM"
    Public Const HAZ_MTL_CD As String = "HAZ_MTL_CD"
    Public Const HAZ_MATL_DSC As String = "HAZ_MATL_DSC"
    Public Const VYG_NO As String = "VYG_NO"
    Public Const VSSL_NM As String = "VSSL_NM"
    Public Const PRT_NM As String = "PRT_NM"
    Public Const PRT_FNC_CD As String = "PRT_FNC_CD"
    Public Const SL_NMBR_4 As String = "SL_NMBR_4"
    Public Const SL_PRTY_4_ID As String = "SL_PRTY_4_ID"
    Public Const SL_PRTY_4_CD As String = "SL_PRTY_4_CD"
    Public Const EST_STTS As String = "EST_STTS"
    Public Const GRSS_WGHT_NC As String = "GRSS_WGHT_NC"
    Public Const TR_WGHT_NC As String = "TR_WGHT_NC"
    Public Const EQPMNT_STTS_DSCRPTN_VC As String = "EQPMNT_STTS_DSCRPTN_VC"

    'Table Name: V_GATEOUT
    Public Const GTOT_BIN As String = "GTOT_BIN"
    Public Const GTOT_TRNSXN As String = "GTOT_TRNSXN"
    Public Const GTOT_CNDTN As String = "GTOT_CNDTN"

    'Table Name: V_REPAIR_ESTIMATE
    Public Const RPR_ESTMT_ID As String = "RPR_ESTMT_ID"
    Public Const RPR_ESTMT_TRNSXN As String = "RPR_ESTMT_TRNSXN"
    Public Const RVSN_NO As String = "RVSN_NO"
    Public Const RPR_ESTMT_DT As String = "RPR_ESTMT_DT"
    Public Const BS_CRRNCY_ID As String = "BS_CRRNCY_ID"
    Public Const BS_CRRNCY_CD As String = "BS_CRRNCY_CD"
    Public Const DPP_CRRNCY_ID As String = "DPP_CRRNCY_ID"
    Public Const DPP_CRRNCY_CD As String = "DPP_CRRNCY_CD"
    Public Const GTN_DT As String = "GTN_DT"
    Public Const TX_RT_NC As String = "TX_RT_NC"
    Public Const SRVC_TX_RT_NC As String = "SRVC_TX_RT_NC"
    Public Const LBR_RT_NC As String = "LBR_RT_NC"
    Public Const ORGNL_ESTMN_DT As String = "ORGNL_ESTMN_DT"
    Public Const YRD_LCTN As String = "YRD_LCTN"
    Public Const LSS_APPRVL_DT As String = "LSS_APPRVL_DT"
    Public Const LSS_APPRVL_AMNT_NC As String = "LSS_APPRVL_AMNT_NC"
    Public Const OWNR_APPRVL_DT As String = "OWNR_APPRVL_DT"
    Public Const OWNR_APPRVL_AMNT_NC As String = "OWNR_APPRVL_AMNT_NC"
    Public Const SRVC_TX_RT As String = "SRVC_TX_RT"
    Public Const SRVYR_NAM As String = "SRVYR_NAM"
    Public Const NTS_VC As String = "NTS_VC"
    Public Const DPP_AMT_NC As String = "DPP_AMT_NC"
    '  Public Const WGHT_NC As String = "WGHT_NC"
    Public Const ESTMTN_TTL_NC As String = "ESTMTN_TTL_NC"
    Public Const TTL_LBR_CST_NC As String = "TTL_LBR_CST_NC"
    Public Const TTL_SRVC_TX_NC As String = "TTL_SRVC_TX_NC"
    Public Const EST_TTL_TXD_NC As String = "EST_TTL_TXD_NC"
    Public Const RDL_ATH_NO As String = "RDL_ATH_NO"
    Public Const EIR_NO As String = "EIR_NO"
    Public Const AUTH_AMNT_NC As String = "AUTH_AMNT_NC"
    Public Const EXCHG_RT_NC As String = "EXCHG_RT_NC"
    Public Const EDI_STTS As String = "EDI_STTS"
    Public Const PCK_DT As String = "PCK_DT"

    Public Const ESTMTN_TYP As String = "ESTMTN_TYP"


    'Table Name: V_REPAIR_ESTIMATE_DETAIL
    Public Const RPR_ESTMT_DTL_ID As String = "RPR_ESTMT_DTL_ID"
    Public Const LBR_RT As String = "LBR_RT"
    Public Const LBR_HRS As String = "LBR_HRS"
    Public Const LBR_HR_CST_NC As String = "LBR_HR_CST_NC"
    Public Const MTRL_CST_NC As String = "MTRL_CST_NC"
    Public Const RSPNSBLTY_ID As String = "RSPNSBLTY_ID"
    Public Const RSPNSBLTY_CD As String = "RSPNSBLTY_CD"
    Public Const TX_RL_ID As String = "TX_RL_ID"
    Public Const TX_RL_CD As String = "TX_RL_CD"
    Public Const TRFF_CD As String = "TRFF_CD"

    'Table Name: V_TRACKING
    Public Const TRCKNG_ID As String = "TRCKNG_ID"
    Public Const RFRNC_NO As String = "RFRNC_NO"
    Public Const PCKP_STTS_VC As String = "PCKP_STTS_VC"
    Public Const PCKP_DT As String = "PCKP_DT"
    Public Const RSND_BT As String = "RSND_BT"
    Public Const ACTVTY_NO As String = "ACTVTY_NO"
    Public Const ACTVTY_RMRKS As String = "ACTVTY_RMRKS"
    Public Const INVCNG_PRTY_ID As String = "INVCNG_PRTY_ID"
    Public Const ACTVTY_DT As String = "ACTVTY_DT"
    Public Const GI_TRNSCTN_NO As String = "GI_TRNSCTN_NO"
    Public Const CNCLD_BY As String = "CNCLD_BY"
    Public Const CNCLD_DT As String = "CNCLD_DT"
    Public Const ADT_RMRKS As String = "ADT_RMRKS"
    Public Const EQPMNT_INFRMTN_RMRKS_VC As String = "EQPMNT_INFRMTN_RMRKS_VC"
    Public Const STTS_ID As String = "STTS_ID"
    Public Const STTS_CD As String = "STTS_CD"


    'Table Name: V_INVENTORY
    Public Const INVNTRY_ID As String = "INVNTRY_ID"
    Public Const EQPMNT_SZ_ID As String = "EQPMNT_SZ_ID"
    Public Const EQPMNT_LNGTH As String = "EQPMNT_LNGTH"
    Public Const EQPMNT_HGT As String = "EQPMNT_HGT"
    Public Const EQPMNT_MTRL As String = "EQPMNT_MTRL"
    Public Const EQPMNT_STTS As String = "EQPMNT_STTS"
    Public Const GT_IN_DT As String = "GT_IN_DT"
    Public Const GT_IN_RMRKS As String = "GT_IN_RMRKS"
    Public Const RPR_ESTMT_NO As String = "RPR_ESTMT_NO"
    Public Const RPR_ESTMT_AMNT As String = "RPR_ESTMT_AMNT"
    Public Const RPR_ESTMT_AMNT_TX As String = "RPR_ESTMT_AMNT_TX"
    Public Const RPR_MTRL_CST_NC As String = "RPR_MTRL_CST_NC"
    Public Const RPR_CLNG_CST_NC As String = "RPR_CLNG_CST_NC"
    Public Const RPR_LBR_CST_NC As String = "RPR_LBR_CST_NC"
    Public Const RPR_ESTMT_RVSN_NO As String = "RPR_ESTMT_RVSN_NO"
    Public Const DPP_AMNT_NC As String = "DPP_AMNT_NC"
    Public Const OWNR_TTL_NC As String = "OWNR_TTL_NC"
    Public Const USR_TTL_NC As String = "USR_TTL_NC"
    Public Const INSRR_TTL_NC As String = "INSRR_TTL_NC"
    Public Const DPT_TTL_NC As String = "DPT_TTL_NC"
    Public Const SPCL_BLLNG_TTL_NC As String = "SPCL_BLLNG_TTL_NC"
    Public Const PRTY_NT_SPCFD_TTL_NC As String = "PRTY_NT_SPCFD_TTL_NC"
    Public Const RPR_RMRKS As String = "RPR_RMRKS"
    Public Const RPR_CMPLTN_DT As String = "RPR_CMPLTN_DT"
    Public Const RPR_CMPLTN_RMRKS As String = "RPR_CMPLTN_RMRKS"
    Public Const SRVYR_NM As String = "SRVYR_NM"
    Public Const SRVY_DT As String = "SRVY_DT"
    Public Const GT_OUT_DT As String = "GT_OUT_DT"

    'Table Name:ESTIMATION_PROCESS
    Public Const SNO As String = "SNO"
    Public Const MTRL_RT_NC As String = "MTRL_RT_NC"
    Public Const TTL_NC As String = "TTL_NC"
    Public Const ESTMT_TTL_NC As String = "ESTMT_TTL_NC"

    'Table Name: DOCUMENT
    Public Const DCMNT_ID As String = "DCMNT_ID"
    Public Const DCMNT_NAM As String = "DCMNT_NAM"
    Public Const DCMNT_DSCRPTN_VC As String = "DCMNT_DSCRPTN_VC"

    'Table Name: DOCUMENT_TEMPLATE
    Public Const DCMNT_TMPLT_ID As String = "DCMNT_TMPLT_ID"
    Public Const TMPLT_NAM As String = "TMPLT_NAM"
    Public Const TMPLT_FL_NAM As String = "TMPLT_FL_NAM"
    Public Const SND_ML_BT As String = "SND_ML_BT"
    Public Const DCMNT_TMPLT_FRMT As String = "DCMNT_TMPLT_FRMT"


    'Table Name: REPORT_SUMMARY_DETAIL
    Public Const USR_LH As String = "USR_LH"
    Public Const INSRR_LH As String = "INSRR_LH"
    Public Const OWNR_LH As String = "OWNR_LH"
    Public Const DPT_LH As String = "DPT_LH"
    Public Const OTHR_LH As String = "OTHR_LH"
    Public Const DLTN_LH As String = "DLTN_LH"
    Public Const USR_LHC As String = "USR_LHC"
    Public Const INSRR_LHC As String = "INSRR_LHC"
    Public Const OWNR_LHC As String = "OWNR_LHC"
    Public Const DPT_LHC As String = "DPT_LHC"
    Public Const OTHR_LHC As String = "OTHR_LHC"
    Public Const DLTN_LHC As String = "DLTN_LHC"
    Public Const USR_MC As String = "USR_MC"
    Public Const INSRR_MC As String = "INSRR_MC"
    Public Const OWNR_MC As String = "OWNR_MC"
    Public Const DPT_MC As String = "DPT_MC"
    Public Const OTHR_MC As String = "OTHR_MC"
    Public Const DLTN_MC As String = "DLTN_MC"
    Public Const USR_TX As String = "USR_TX"
    Public Const INSRR_TX As String = "INSRR_TX"
    Public Const OWNR_TX As String = "OWNR_TX"
    Public Const DPT_TX As String = "DPT_TX"
    Public Const OTHR_TX As String = "OTHR_TX"
    Public Const DLTN_TX As String = "DLTN_TX"
    Public Const USR_TTL As String = "USR_TTL"
    Public Const INSRR_TTL As String = "INSRR_TTL"
    Public Const OWNR_TTL As String = "OWNR_TTL"
    Public Const DPT_TTL As String = "DPT_TTL"
    Public Const OTHR_TTL As String = "OTHR_TTL"
    Public Const DLTN_TTL As String = "DLTN_TTL"
    Public Const TTL_EST_CST As String = "TTL_EST_CST"
    Public Const TTL_CLN_CST As String = "TTL_CLN_CST"
    Public Const TTL_LBR_CST As String = "TTL_LBR_CST"
    Public Const TTL_SRVC_CST As String = "TTL_SRVC_CST"
    Public Const TTL_EST_SRVC_CST As String = "TTL_EST_SRVC_CST"
    Public Const RPR_CD As String = "RPR_CD"
    Public Const RPR_DSCRPTN_VC As String = "RPR_DSCRPTN_VC"
    Public Const DMG_DSCRPTN_VC As String = "DMG_DSCRPTN_VC"
    Public Const CMPNNT_DSCRPTN_VC As String = "CMPNNT_DSCRPTN_VC"

    'Data Tables..
    Public Const _CONFIG As String = "CONFIG"
    Public Const _CONFIG_TEMPLATE As String = "CONFIG_TEMPLATE"

    'Data Columns..

    'Table Name: CONFIG
    Public Const CNFG_ID As String = "CNFG_ID"
    Public Const CNFG_TMPLT_ID As String = "CNFG_TMPLT_ID"
    Public Const KY_NAM As String = "KY_NAM"
    Public Const KY_DSCRPTION As String = "KY_DSCRPTION"
    Public Const KY_VL As String = "KY_VL"
    Public Const ENBLD_BT As String = "ENBLD_BT"

    'Table Name: CONFIG_TEMPLATE
    Public Const CNFG_TYP As String = "CNFG_TYP"

    'Table Name: V_RPT_PENDINGINVOICE
    Public Const STRG_CHRG_ID As String = "STRG_CHRG_ID"
    Public Const CST_TYP As String = "CST_TYP"
    Public Const RFRNC_EIR_NO_1 As String = "RFRNC_EIR_NO_1"
    Public Const RFRNC_EIR_NO_2 As String = "RFRNC_EIR_NO_2"
    Public Const FRM_BLLNG_DT As String = "FRM_BLLNG_DT"
    Public Const TO_BLLNG_DT As String = "TO_BLLNG_DT"
    Public Const FR_DYS As String = "FR_DYS"
    Public Const NO_OF_DYS As String = "NO_OF_DYS"
    Public Const STRG_TX_RT_NC As String = "STRG_TX_RT_NC"
    Public Const TTL_CSTS_NC As String = "TTL_CSTS_NC"
    Public Const IS_GT_OT_FLG As String = "IS_GT_OT_FLG"
    Public Const IS_LT_FLG As String = "IS_LT_FLG"
    Public Const BLLNG_FLG As String = "BLLNG_FLG"
    Public Const STRG_CNTN_FLG As String = "STRG_CNTN_FLG"
    Public Const BLLNG_TYP_CD As String = "BLLNG_TYP_CD"
    Public Const MODE_PYMNT As String = "MODE_PYMNT"
    Public Const PTI_RT As String = "PTI_RT"
    Public Const HNDLNG_CHRG_NC As String = "HNDLNG_CHRG_NC"
    Public Const WSHNG_CHRG_NC As String = "WSHNG_CHRG_NC"
    Public Const STRG_CST_NC As String = "STRG_CST_NC"
    Public Const LFT_CHRG_NC As String = "LFT_CHRG_NC"
    Public Const DAYS As String = "DAYS"
    Public Const STORAGE As String = "STORAGE"
    Public Const LIFTS As String = "LIFTS"
    Public Const PERIODFROM As String = "PERIODFROM"
    Public Const PERIODTO As String = "PERIODTO"


    Public Const EQPMNT_TYP_DSCRPTN_VC As String = "EQPMNT_TYP_DSCRPTN_VC"

    Public Const WF_ACTIVITY_ID As String = "WF_ACTIVITY_ID"
    Public Const WF_ACTIVITY_NAME As String = "WF_ACTIVITY_NAME"
    Public Const PENDING_STATUS As String = "PENDING_STATUS"
    Public Const DEFAULT_STATUS As String = "DEFAULT_STATUS"
    Public Const DEFAULT_STATUS_ID As String = "DEFAULT_STATUS_ID"
    Public Const EQUIPMENT_TYPE As String = "EQUIPMENT_TYPE"
    Public Const EQUIPMENT_CODE As String = "EQUIPMENT_CODE"
    Public Const WF_STATUS_ID As String = "WF_STATUS_ID"

    ''SERVICE_PARTNER
    Public Const SRVC_PRTNR_ID As String = "SRVC_PRTNR_ID"
    Public Const SRVC_PRTNR_ACTL_ID As String = "SRVC_PRTNR_ACTL_ID"
    Public Const SRVC_PRTNR_TYP_CD As String = "SRVC_PRTNR_TYP_CD"
    Public Const SRVC_PRTNR_CD As String = "SRVC_PRTNR_CD"
    Public Const SRVC_PRTNR_NAM As String = "SRVC_PRTNR_NAM"


    'Attachment
    Public Const ATTCHMNT_ID As String = "ATTCHMNT_ID"
    Public Const ATTCHMNT_PTH As String = "ATTCHMNT_PTH"
    Public Const ACTL_FL_NM As String = "ACTL_FL_NM"

    'Table Name: CLEANING_CHARGE
    Public Const CLNNG_CHRG_ID As String = "CLNNG_CHRG_ID"
    Public Const CLNNG_ID As String = "CLNNG_ID"
    Public Const ORGNL_CLNNG_DT As String = "ORGNL_CLNNG_DT"
    Public Const ORGNL_INSPCTD_DT As String = "ORGNL_INSPCTD_DT"
    Public Const CLNNG_RT As String = "CLNNG_RT"
    Public Const CLNNG_CERT_NO As String = "CLNNG_CERT_NO"
    Public Const DRFT_INVC_NO As String = "DRFT_INVC_NO"
    Public Const FNL_INVC_NO As String = "FNL_INVC_NO"

    'Table Name: HANDLING_CHARGE
    Public Const HNDLNG_CHRG_ID As String = "HNDLNG_CHRG_ID"
    Public Const HNDLNG_CST_NC As String = "HNDLNG_CST_NC"
    Public Const HNDLNG_TX_RT_NC As String = "HNDLNG_TX_RT_NC"
    Public Const HTNG_BT As String = "HTNG_BT"
    Public Const FROM_BILLING_DATE As String = "FROM_BILLING_DATE"
    Public Const TO_BILLING_DATE As String = "TO_BILLING_DATE"

    'Table Name: HEATING_CHARGE
    Public Const HTNG_ID As String = "HTNG_ID"
    Public Const HTNG_CD As String = "HTNG_CD"
    Public Const HTNG_STRT_DT As String = "HTNG_STRT_DT"
    Public Const HTNG_STRT_TM As String = "HTNG_STRT_TM"
    Public Const HTNG_END_DT As String = "HTNG_END_DT"
    Public Const HTNG_END_TM As String = "HTNG_END_TM"
    Public Const HTNG_TMPRTR As String = "HTNG_TMPRTR"
    Public Const TTL_HTN_PRD As String = "TTL_HTN_PRD"
    Public Const MIN_HTNG_RT_NC As String = "MIN_HTNG_RT_NC"
    Public Const HRLY_CHRG_NC As String = "HRLY_CHRG_NC"
    Public Const TTL_RT_NC As String = "TTL_RT_NC"

    'Table Name: INVOICE_HISTORY
    Public Const INVC_BIN As String = "INVC_BIN"
    Public Const INVC_NO As String = "INVC_NO"
    Public Const INVC_DT As String = "INVC_DT"
    Public Const INVC_FL_PTH As String = "INVC_FL_PTH"
    Public Const INVC_TYP As String = "INVC_TYP"
    Public Const INVC_CRRNCY_ID As String = "INVC_CRRNCY_ID"
    Public Const EXCHNG_RT_NC As String = "EXCHNG_RT_NC"
    Public Const CSTMR_CRRNCY_ID As String = "CSTMR_CRRNCY_ID"
    Public Const BLLNG_TYP_ID As String = "BLLNG_TYP_ID"
    Public Const TTL_CST_IN_CSTMR_CRRNCY_NC As String = "TTL_CST_IN_CSTMR_CRRNCY_NC"
    Public Const TTL_CST_IN_INVC_CRRNCY_NC As String = "TTL_CST_IN_INVC_CRRNCY_NC"
    Public Const NO_OF_EQPMNT As String = "NO_OF_EQPMNT"

    'Table Name: MISCELLANEOUS_INVOICE
    Public Const MSCLLNS_INVC_ID As String = "MSCLLNS_INVC_ID"
    Public Const NO_OF_EQPMNT_NO As String = "NO_OF_EQPMNT_NO"
    Public Const INVCNG_TO_ID As String = "INVCNG_TO_ID"
    Public Const CHRG_DSCRPTN As String = "CHRG_DSCRPTN"
    Public Const AMNT_NC As String = "AMNT_NC"

    'Table Name: REPAIR_CHARGE
    Public Const RPR_CHRG_ID As String = "RPR_CHRG_ID"
    Public Const ESTMT_NO As String = "ESTMT_NO"
    Public Const RPR_APPRVL_DT As String = "RPR_APPRVL_DT"
    Public Const LBR_CST_NC As String = "LBR_CST_NC"
    Public Const RPR_TX_RT_NC As String = "RPR_TX_RT_NC"
    Public Const RPR_TX_AMNT_NC As String = "RPR_TX_AMNT_NC"
    Public Const RPR_APPRVL_AMNT_NC As String = "RPR_APPRVL_AMNT_NC"
    Public Const CLN_CST_NC As String = "CLN_CST_NC"
    Public Const TTL_SRV_TAX As String = "TTL_SRV_TAX"
    Public Const TTL_EST_INCL_SRV_TAX As String = "TTL_EST_INCL_SRV_TAX"
    Public Const INVC_TYPE As String = "INVC_TYPE"

    'Table Name: STORAGE_CHARGE
    Public Const BLLNG_TLL_DT As String = "BLLNG_TLL_DT"

    'Table Name: V_INVOICE_HISTORY
    Public Const INVC_CRRNCY_CD As String = "INVC_CRRNCY_CD"
    Public Const CSTMR_CRRNCY_CD As String = "CSTMR_CRRNCY_CD"
    Public Const SRVC_PRTNR_NM As String = "SRVC_PRTNR_NM"
    Public Const FL_NM As String = "FL_NM"

    Public Const HANDLINGSTORAGE_INVOICE_DRAFT As String = "HANDLINGSTORAGE_INVOICE_DRAFT"
    Public Const REPAIR_INVOICE_DRAFT As String = "REPAIR_INVOICE_DRAFT"
    Public Const CLEANING_INVOICE_DRAFT As String = "CLEANING_INVOICE_DRAFT"
    Public Const MISCELLANEOUS_INVOICE_DRAFT As String = "MISCELLANEOUS_INVOICE_DRAFT"
    Public Const HEATING_INVOICE_DRAFT As String = "HEATING_INVOICE_DRAFT"
    Public Const TRANSPORTATION_INVOICE_DRAFT As String = "TRANSPORTATION_INVOICE_DRAFT"
    Public Const RENTAL_INVOICE_DRAFT As String = "RENTAL_INVOICE_DRAFT"
    Public Const FINAL_INVOICE As String = "FINAL_INVOICE"
    Public Const CREDITNOTE_INVOICE_DRAFT As String = "CREDITNOTE_INVOICE_DRAFT"
    Public Const INSPECTION_INVOICE_DRAFT As String = "INSPECTION_INVOICE_DRAFT"

    'Table Name: HANDLING_CHARGE
    Public Const FROM_DATE As String = "FROM_DATE"
    Public Const TO_DATE As String = "TO_DATE"

    'Table Name: V_HANDLING_CHARGE
    Public Const PRDCT_CD As String = "PRDCT_CD"
    Public Const STORAGE_DAYS As String = "STORAGE_DAYS"
    Public Const CHARGEABLE_DAYS As String = "CHARGEABLE_DAYS"

    'Table Name: HANDLING_STORAGE_INVOCIE
    Public Const HNDLNG_STRG_ID As String = "HNDLNG_STRG_ID"
    Public Const HNDIN_CHRG As String = "HNDIN_CHRG"
    Public Const HNDOUT_CHRG As String = "HNDOUT_CHRG"
    Public Const STRG_CHRG As String = "STRG_CHRG"
    Public Const CHECKED As String = "CHECKED"
    Public Const HNDIN As String = "HNDIN"
    Public Const HNDOT As String = "HNDOT"
    Public Const STR As String = "STR"
    Public Const AGNT_ID As String = "AGNT_ID"
    'Table Name: EXCHANGE RATE
    Public Const FRM_CRRNCY_CD As String = "FRM_CRRNCY_CD"
    Public Const TO_CRRNCY_CD As String = "TO_CRRNCY_CD"
    Public Const EXCHNG_RT_PR_UNT_NC As String = "EXCHNG_RT_PR_UNT_NC"

    'Table Name: CUSTOMER_STORAGE_DETAIL
    Public Const CSTMR_STRG_DTL_ID As String = "CSTMR_STRG_DTL_ID"
    Public Const UP_TO_DYS As String = "UP_TO_DYS"
    Public Const STRG_CHRG_NC As String = "STRG_CHRG_NC"
    Public Const RMRKS_VC As String = "RMRKS_VC"

    'Table Name: V_CUSTOMER
    Public Const CNTCT_ADDRSS As String = "CNTCT_ADDRSS"
    Public Const BLLNG_ADDRSS As String = "BLLNG_ADDRSS"
    Public Const RPRTNG_EML_ID As String = "RPRTNG_EML_ID"
    Public Const INVCNG_EML_ID As String = "INVCNG_EML_ID"
    Public Const RPR_TCH_EML_ID As String = "RPR_TCH_EML_ID"
    Public Const BLK_EML_FRMT_ID As String = "BLK_EML_FRMT_ID"
    Public Const BLK_EML_FRMT_CD As String = "BLK_EML_FRMT_CD"
    Public Const HYDR_AMNT_NC As String = "HYDR_AMNT_NC"
    Public Const PNMTC_AMNT_NC As String = "PNMTC_AMNT_NC"
    Public Const LBR_RT_PR_HR_NC As String = "LBR_RT_PR_HR_NC"
    Public Const LK_TST_RT_NC As String = "LK_TST_RT_NC"
    Public Const SRVY_ONHR_OFFHR_RT_NC As String = "SRVY_ONHR_OFFHR_RT_NC"
    Public Const PRDC_TST_TYP_ID As String = "PRDC_TST_TYP_ID"
    Public Const PRDC_TST_TYP_CD As String = "PRDC_TST_TYP_CD"
    Public Const VLDTY_PRD_TST_YRS As String = "VLDTY_PRD_TST_YRS"
    Public Const CHK_DGT_VLDTN_BT As String = "CHK_DGT_VLDTN_BT"
    Public Const TRNSPRTTN_BT As String = "TRNSPRTTN_BT"
    Public Const RNTL_BT As String = "RNTL_BT"

    'Table Name: V_REPAIR_CHARGE
    Public Const INVCNG_PRTY_CD As String = "INVCNG_PRTY_CD"
    Public Const INVCNG_PRTY_NM As String = "INVCNG_PRTY_NM"
    Public Const LEAK_TEST As String = "LEAK_TEST"
    Public Const PTI As String = "PTI"
    Public Const SURVEY As String = "SURVEY"
    Public Const TOTALAMOUNT As String = "TOTALAMOUNT"
    Public Const REPAIRS As String = "REPAIRS"

    'Table Name: V_CLEANING_CHARGE
    Public Const PRDCT_DSCRPTN_VC As String = "PRDCT_DSCRPTN_VC"

    'Table Name: V_MISCELLANEOUS_INVOICE
    Public Const INVCNG_TO_CD As String = "INVCNG_TO_CD"
    Public Const INVCNG_TO_NAM As String = "INVCNG_TO_NAM"

    'Table Name: V_HEATING_CHARGE
    Public Const HTNG_STRT_DT_TM As String = "HTNG_STRT_DT_TM"
    Public Const HTNG_END_DT_TM As String = "HTNG_END_DT_TM"

    'Table Name: V_EXCHANGE_RATE
    Public Const EXCHNG_RT_ID As String = "EXCHNG_RT_ID"
    Public Const FRM_CRRNCY_ID As String = "FRM_CRRNCY_ID"
    Public Const TO_CRRNCY_ID As String = "TO_CRRNCY_ID"
    Public Const WTH_EFFCT_FRM_DT As String = "WTH_EFFCT_FRM_DT"

    'Table Name: V_BANK_DETAIL
    Public Const BNK_DTL_BIN As String = "BNK_DTL_BIN"
    Public Const BNK_TYP_ID As String = "BNK_TYP_ID"
    Public Const BNK_TYP_CD As String = "BNK_TYP_CD"
    Public Const BNK_NM As String = "BNK_NM"
    Public Const BNK_ADDRSS As String = "BNK_ADDRSS"
    Public Const ACCNT_NO As String = "ACCNT_NO"
    Public Const IBAN_NO As String = "IBAN_NO"
    Public Const SWIFT_CD As String = "SWIFT_CD"
    Public Const CRRNCY_CD As String = "CRRNCY_CD"

    'Table Name: V_DAR_ACTIVITY_STATUS
    Public Const ACTVTY_STTS_ID As String = "ACTVTY_STTS_ID"
    Public Const GTOT_DT As String = "GTOT_DT"
    Public Const PRDCT_ID As String = "PRDCT_ID"
    Public Const CLNNG_DT As String = "CLNNG_DT"
    Public Const INVC_GNRT_BT As String = "INVC_GNRT_BT"
    Public Const GI_RF_NO As String = "GI_RF_NO"
    Public Const INSTRCTNS_VC As String = "INSTRCTNS_VC"
    Public Const CERT_GNRTD_FLG As String = "CERT_GNRTD_FLG"
    Public Const CHMCL_NM As String = "CHMCL_NM"
    Public Const CRT_GNRTD_FLG As String = "CRT_GNRTD_FLG"
    Public Const INSPCTN_DT As String = "INSPCTN_DT"
    Public Const NEXT_TEST_DATE As String = "NEXT_TEST_DATE"
    Public Const ASRMRKS As String = "ASRMRKS"
    Public Const RMRKS As String = "RMRKS"
    Public Const NM As String = "NM"
    Public Const NY As String = "NY"
    Public Const CM As String = "CM"
    Public Const CY As String = "CY"
    Public Const REMARKS As String = "REMARKS"
    Public Const NXT_TYP_ID As String = "NXT_TYP_ID"
    Public Const NXT_TYP_CD As String = "NXT_TYP_CD"
    Public Const GTAPPRVL_DT As String = "GTAPPRVL_DT"
    Public Const EIR_NO_OUT As String = "EIR_NO_OUT"

    'Table Name: V_DAR_CUSTOMER_SUMMARY
    Public Const IND As String = "IND"
    Public Const PHL As String = "PHL"
    Public Const ACN As String = "ACN"
    Public Const AWECLN As String = "AWECLN"
    Public Const AWE As String = "AWE"
    Public Const AAR As String = "AAR"
    Public Const AUR As String = "AUR"
    Public Const ASR As String = "ASR"
    Public Const SRV As String = "SRV"
    Public Const AVLCLN As String = "AVLCLN"
    Public Const AVLCLNRPC As String = "AVLCLNRPC"
    Public Const RPC As String = "RPC"
    Public Const STO As String = "STO"
    Public Const AVL As String = "AVL"
    Public Const OUT As String = "OUT"
    Public Const TOTAL As String = "TOTAL"
    Public Const LST_TST_DT As String = "LST_TST_DT"
    Public Const NXT_TST_DT As String = "NXT_TST_DT"
    Public Const LST_TST_TYP_ID As String = "LST_TST_TYP_ID"
    Public Const NXT_TST_TYP_ID As String = "NXT_TST_TYP_ID"
    Public Const TEST_STATUS_ID As String = "TEST_STATUS_ID"
    Public Const RPR_TYP_ID As String = "RPR_TYP_ID"

    'Table Name: V_TRANSPORTATION_INVOICE
    Public Const TRNSPRTTN_CHRG_ID As String = "TRNSPRTTN_CHRG_ID"
    Public Const TRNSPRTTN_ID As String = "TRNSPRTTN_ID"
    Public Const EQPMNT_STT_ID As String = "EQPMNT_STT_ID"
    Public Const EQPMNT_STT_CD As String = "EQPMNT_STT_CD"
    Public Const RQST_NO As String = "RQST_NO"
    Public Const CSTMR_RF_NO As String = "CSTMR_RF_NO"
    Public Const RT_ID As String = "RT_ID"
    Public Const RT_CD As String = "RT_CD"
    Public Const RT_DSCRPTN_VC As String = "RT_DSCRPTN_VC"
    Public Const EVNT_DT As String = "EVNT_DT"
    Public Const TRP_RT_NC As String = "TRP_RT_NC"
    Public Const WGHTMNT_AMNT_NC As String = "WGHTMNT_AMNT_NC"
    Public Const TKN_AMNT_NC As String = "TKN_AMNT_NC"
    Public Const RCHRGBL_CST_AMNT_NC As String = "RCHRGBL_CST_AMNT_NC"
    Public Const FNNC_CHRG_AMNT_NC As String = "FNNC_CHRG_AMNT_NC"
    Public Const DTNTN_AMNT_NC As String = "DTNTN_AMNT_NC"
    Public Const OTHR_CHRG_AMNT_NC As String = "OTHR_CHRG_AMNT_NC"
    Public Const DPT_AMNT As String = "DPT_AMNT"
    Public Const CSTMR_AMNT As String = "CSTMR_AMNT"
    Public Const DPT_CRRNCY_ID As String = "DPT_CRRNCY_ID"
    Public Const DPT_CRRNCY_CD As String = "DPT_CRRNCY_CD"
    Public Const JB_STRT_DT As String = "JB_STRT_DT"
    Public Const JB_END_DT As String = "JB_END_DT"

    Public Const PCK_UP_LCTN_CD As String = "PCK_UP_LCTN_CD"
    Public Const PCK_UP_LCTN_DSCRPTN_VC As String = "PCK_UP_LCTN_DSCRPTN_VC"
    Public Const DRP_OFF_LCTN_CD As String = "DRP_OFF_LCTN_CD"
    Public Const DRP_OFF_LCTN_DSCRPTN_VC As String = "DRP_OFF_LCTN_DSCRPTN_VC"
    Public Const ACTVTY_CD As String = "ACTVTY_CD"
    Public Const ACTVTY_LCTN_CD As String = "ACTVTY_LCTN_CD"
    Public Const ACTVTY_LCTN_DSCRPTN_VC As String = "ACTVTY_LCTN_DSCRPTN_VC"
    Public Const ADDTNL_CHRG_RT_NC As String = "ADDTNL_CHRG_RT_NC"
    Public Const TRP_TM As String = "TRP_TM"
    Public Const EMPTY_EQPMNT As String = "EMPTY_EQPMNT"
    Public Const FULL_EQPMNT As String = "FULL_EQPMNT"
    Public Const NO_OF_TRIPS As String = "NO_OF_TRIPS"
    Public Const RPR_TYP_CD As String = "RPR_TYP_CD"
    Public Const TRNSPRTTN_DTL_ID As String = "TRNSPRTTN_DTL_ID"


    'Table Name: INVOICE_HISTORY_DETAIL
    Public Const INVC_HSTRY_DTL_ID As String = "INVC_HSTRY_DTL_ID"
    Public Const RNTL_RFRNC_NO As String = "RNTL_RFRNC_NO"
    Public Const HNDLNG_IN_AMNT_NC As String = "HNDLNG_IN_AMNT_NC"
    Public Const HNDLNG_OT_AMNT_NC As String = "HNDLNG_OT_AMNT_NC"
    Public Const STRG_AMNT_NC As String = "STRG_AMNT_NC"
    Public Const DPT_AMNT_NC As String = "DPT_AMNT_NC"
    Public Const CSTMR_AMNT_NC As String = "CSTMR_AMNT_NC"
    Public Const STRG_DYS As String = "STRG_DYS"

    'Table Name: AUDIT_LOG
    Public Const ADT_LG_ID As String = "ADT_LG_ID"
    Public Const ACTN_VC As String = "ACTN_VC"
    Public Const ACTN_DT As String = "ACTN_DT"
    Public Const OLD_VL As String = "OLD_VL"
    Public Const NEW_VL As String = "NEW_VL"
    Public Const RSN_VC As String = "RSN_VC"

    'Table Name: V_RENTAL_CHARGE
    Public Const ON_HR_DT As String = "ON_HR_DT"
    Public Const OFF_HR_DT As String = "OFF_HR_DT"
    Public Const RNTL_CHRG_ID As String = "RNTL_CHRG_ID"
    Public Const RNTL_TYP As String = "RNTL_TYP"
    Public Const ON_HR_SRVY_NC As String = "ON_HR_SRVY_NC"
    Public Const OFF_HR_SRVY_NC As String = "OFF_HR_SRVY_NC"
    Public Const RNTL_PR_DY_NC As String = "RNTL_PR_DY_NC"
    Public Const RNTL_TX_RT_NC As String = "RNTL_TX_RT_NC"
    Public Const RNTL_CNTN_FLG As String = "RNTL_CNTN_FLG"
    Public Const IS_GT_IN_FLG As String = "IS_GT_IN_FLG"
    Public Const RNTL_DYS As String = "RNTL_DYS"
    Public Const RNTL_CHRG_NC As String = "RNTL_CHRG_NC"
    Public Const HNDLNG_IN_NC As String = "HNDLNG_IN_NC"
    Public Const HNDLNG_OT_NC As String = "HNDLNG_OT_NC"
    Public Const OTHR_CHRG_NC As String = "OTHR_CHRG_NC"
    Public Const RNTL_CSTMR_ID As String = "RNTL_CSTMR_ID"
    Public Const ON_HR_BLLNG_FLG As String = "ON_HR_BLLNG_FLG"
    Public Const OFF_HR_BLLNG_FLG As String = "OFF_HR_BLLNG_FLG"
    Public Const CRRNCY_DSCRPTN_VC As String = "CRRNCY_DSCRPTN_VC"

    'Finance Rental Revenue
    Public Const ON_HR_EQPMNT As String = "ON_HR_EQPMNT"
    Public Const OFF_HR_EQPMNT As String = "OFF_HR_EQPMNT"
    Public Const RNTL_CHRG_EQPMNT As String = "RNTL_CHRG_EQPMNT"
    Public Const TTL_RNTL_CHARG_NC As String = "TTL_RNTL_CHARG_NC"
    Public Const TTL_RNTL_PRD_DYS As String = "TTL_RNTL_PRD_DYS"
    Public Const CSTMR_CD_DSPLY As String = "CSTMR_CD_DSPLY"

    Public Const PERD_FRM_DT As String = "PERD_FRM_DT"
    Public Const PERD_TO_DT As String = "PERD_TO_DT"
    Public Const SLNO As String = "SLNO"

    'Transporter (Activity Submit)
    Public Const TRNSPRTR_ID As String = "TRNSPRTR_ID"
    Public Const TRNSPRTR_DSCRPTN As String = "TRNSPRTR_DSCRPTN"

    Public Const ADDTNL_CLNNG_CHRG_NC As String = "ADDTNL_CLNNG_CHRG_NC"
    Public Const COUNT_EQPMNT_NO As String = "COUNT_EQPMNT_NO"

    Public Const ACTVTY_SBMT_ID As String = "ACTVTY_SBMT_ID"
    Public Const PG_NM As String = "PG_NM"
    Public Const CMPR_FLG As String = "CMPR_FLG"
    Public Const CMPR_TBL_NM As String = "CMPR_TBL_NM"
    Public Const FLTR_CNDTN As String = "FLTR_CNDTN"
    Public Const CMPR_FLTR_CNDTN As String = "CMPR_FLTR_CNDTN"
    Public Const ORDR_BY As String = "ORDR_BY"
    Public Const TABLE_NAME As String = "TABLE_NAME"

    Public Const CMMNTS_VC As String = "CMMNTS_VC"


    'Table Name: V_CLEANING_METHOD_DETAIL

    Public Const CLNNG_TYP_CD As String = "CLNNG_TYP_CD"
    Public Const CLNNG_TYP_DSCRPTN_VC As String = "CLNNG_TYP_DSCRPTN_VC"

    Public Const ADDTNL_CLNNG_BT As String = "ADDTNL_CLNNG_BT"

    'Table Name : INDEX_PATTERN
    Public Const INDX_PTTRN_FRMT As String = "INDX_PTTRN_FRMT"
    Public Const SPLT_CHR As String = "SPLT_CHR"
    Public Const RST_BSS_ID As String = "RST_BSS_ID"
    Public Const INDX_PTTRN_ID As String = "INDX_PTTRN_ID"
    Public Const FLD_NM As String = "FLD_NM"
    Public Const STRT_CHR As String = "STRT_CHR"
    Public Const END_CHR As String = "END_CHR"
    Public Const SQNC_NO As String = "SQNC_NO"
    Public Const SQNC_CNDTN_VAL = "SQNC_CNDTN_VAL"
    Public Const INDX_BSS_ID As String = "INDX_BSS_ID"
    Public Const MX_SNO_ID As String = "MX_SNO_ID"
    Public Const MX_RFRNC_NO As String = "MX_RFRNC_NO"
    Public Const MX_SN_DTL_ID As String = "MX_SN_DTL_ID"
    Public Const SQNC_NO_STRT As String = "SQNC_NO_STRT"
    Public Const NO_OF_DGT As String = "NO_OF_DGT"
    Public Const SCRN_NM As String = "SCRN_NM"
    Public Const INDX_BSS_FLD_NM As String = "INDX_BSS_FLD_NM"
    Public Const RST_CNDTN_VAL As String = "RST_CNDTN_VAL"

    'Table Name : V_INSPECTION_CHARGES
    Public Const INSPCTN_CHRG_ID As String = "INSPCTN_CHRG_ID"
    Public Const CSTMR_AGNT_ID As String = "CSTMR_AGNT_ID"
    Public Const INSPCTN_CHRG As String = "INSPCTN_CHRG"

#End Region

End Class


#End Region

