#Region "BulkEmailData"
Public Class EmailData

#Region "Declaration Part.."
    'Data Tables..
    Public Const _BULK_EMAIL As String = "BULK_EMAIL"
    Public Const _BULK_EMAIL_DETAIL As String = "BULK_EMAIL_DETAIL"
    Public Const _TRACKING As String = "TRACKING"
    Public Const _REPAIR_ESTIMATE As String = "REPAIR_ESTIMATE"
    Public Const _REPAIR_ESTIMATE_DETAIL As String = "REPAIR_ESTIMATE_DETAIL"
    Public Const _V_REPAIR_ESTIMATE As String = "V_REPAIR_ESTIMATE"
    Public Const _V_REPAIR_ESTIMATE_DETAIL As String = "V_REPAIR_ESTIMATE_DETAIL"
    Public Const _REPAIR_SUMMARY_DETAIL As String = "REPAIR_SUMMARY_DETAIL"
    Public Const _SUMMARY_DETAIL = "SUMMARY_DETAIL"


    'Data Columns..

    'Table Name: BULK_EMAIL

    Public Const BLK_EML_BIN As String = "BLK_EML_BIN"
    Public Const FRM_EML As String = "FRM_EML"
    Public Const TO_EML As String = "TO_EML"
    Public Const SBJCT_VC As String = "SBJCT_VC"
    Public Const BDY_VC As String = "BDY_VC"
    Public Const SNT_DT As String = "SNT_DT"
    Public Const CRTD_DT As String = "CRTD_DT"
    Public Const CRTD_BY As String = "CRTD_BY"
    Public Const ACTV_BT As String = "ACTV_BT"
    Public Const DPT_ID As String = "DPT_ID"

    'Table Name: BULK_EMAIL_DETAIL
    Public Const BLK_EML_DTL_BIN As String = "BLK_EML_DTL_BIN"
    Public Const ACTVTY_NAM As String = "ACTVTY_NAM"
    Public Const TRNSMSSN_NO As String = "TRNSMSSN_NO"
    Public Const EQPMNT_NO As String = "EQPMNT_NO"
    Public Const STTS_VC As String = "STTS_VC"

    'Table Name: TRACKING
    Public Const TRCKNG_ID As String = "TRCKNG_ID"
    Public Const RFRNC_NO As String = "RFRNC_NO"
    Public Const EIR_DT As String = "EIR_DT"
    Public Const PCKP_STTS_VC As String = "PCKP_STTS_VC"
    Public Const PCKP_DT As String = "PCKP_DT"
    Public Const RSND_BT As String = "RSND_BT"

    'Table Name: REPAIR_ESTIMATE
    Public Const RPR_ESTMT_ID As String = "RPR_ESTMT_ID"
    Public Const RPR_ESTMT_TRNSXN As String = "RPR_ESTMT_TRNSXN"
    Public Const RVSN_NO As String = "RVSN_NO"
    Public Const RPR_ESTMT_DT As String = "RPR_ESTMT_DT"
    Public Const LSS_ID As String = "LSS_ID"
    Public Const EQPMNT_TYP_ID As String = "EQPMNT_TYP_ID"
    Public Const EQPMNT_CD_ID As String = "EQPMNT_CD_ID"
    Public Const EQPMNT_SZ_ID As String = "EQPMNT_SZ_ID"
    Public Const GTN_DT As String = "GTN_DT"
    Public Const LST_OH_LOC As String = "LST_OH_LOC"
    Public Const LST_OH_DT As String = "LST_OH_DT"
    Public Const EQPMNT_STTS_ID As String = "EQPMNT_STTS_ID"
    Public Const MNFCTR_DT As String = "MNFCTR_DT"
    Public Const CSTMR_ID As String = "CSTMR_ID"
    Public Const SRVYR_NAM As String = "SRVYR_NAM"
    Public Const TX_RT_NC As String = "TX_RT_NC"
    Public Const NTS_VC As String = "NTS_VC"
    Public Const BS_CRRNCY_ID As String = "BS_CRRNCY_ID"
    Public Const LBR_RT_NC As String = "LBR_RT_NC"
    Public Const DPP_CRRNCY_ID As String = "DPP_CRRNCY_ID"
    Public Const DPP_AMT_NC As String = "DPP_AMT_NC"
    Public Const WGHT_NC As String = "WGHT_NC"
    Public Const MSR_ID As String = "MSR_ID"
    Public Const UNT_ID As String = "UNT_ID"
    Public Const ESTMTN_TTL_NC As String = "ESTMTN_TTL_NC"
    Public Const RDL_ATH_NO As String = "RDL_ATH_NO"
    Public Const EIR_NO As String = "EIR_NO"
    Public Const AUTH_AMNT_NC As String = "AUTH_AMNT_NC"
    Public Const ORGNL_ESTMN_DT As String = "ORGNL_ESTMN_DT"
    Public Const EXCHG_RT_NC As String = "EXCHG_RT_NC"
    Public Const EDI_STTS As String = "EDI_STTS"
    Public Const PCK_DT As String = "PCK_DT"
    Public Const EST_STTS As String = "EST_STTS"
    Public Const EST_TTL_TXD_NC As String = "EST_TTL_TXD_NC"
    Public Const SRVC_TX_RT_NC As String = "SRVC_TX_RT_NC"
    Public Const TTL_LBR_CST_NC As String = "TTL_LBR_CST_NC"
    Public Const TTL_SRVC_TX_NC As String = "TTL_SRVC_TX_NC"
    Public Const YRD_LCTN As String = "YRD_LCTN"
    Public Const RC_EST_STTS As String = "RC_EST_STTS"
    Public Const ESTMTN_TYP As String = "ESTMTN_TYP"

    'Table Name: REPAIR_ESTIMATE_DETAIL
    Public Const RPR_ESTMT_DTL_ID As String = "RPR_ESTMT_DTL_ID"
    Public Const CMMNTS As String = "CMMNTS"
    Public Const LINE As String = "LINE"
    Public Const RPR_ID As String = "RPR_ID"
    Public Const QTY As String = "QTY"
    Public Const DMG_ID As String = "DMG_ID"
    Public Const CMPNNT_ID As String = "CMPNNT_ID"
    Public Const MTRL_ID As String = "MTRL_ID"
    Public Const LCTN_CD As String = "LCTN_CD"
    Public Const LNGTH_NC As String = "LNGTH_NC"
    Public Const WDTH_NC As String = "WDTH_NC"
    Public Const HIGHT_NC As String = "HIGHT_NC"
    Public Const LBR_RT As String = "LBR_RT"
    Public Const LBR_HRS As String = "LBR_HRS"
    Public Const LBR_HR_CST_NC As String = "LBR_HR_CST_NC"
    Public Const MTRL_CST_NC As String = "MTRL_CST_NC"
    Public Const RSPNSBLTY_ID As String = "RSPNSBLTY_ID"
    Public Const TX_RL_ID As String = "TX_RL_ID"
    Public Const DMG_RPR_DSCRPTN As String = "DMG_RPR_DSCRPTN"
    Public Const TRFF_CD As String = "TRFF_CD"

    'Table Name: V_REPAIR_ESTIMATE
    Public Const LSS_APPRVL_DT As String = "LSS_APPRVL_DT"
    Public Const LSS_APPRVL_AMNT_NC As String = "LSS_APPRVL_AMNT_NC"
    Public Const OWNR_APPRVL_DT As String = "OWNR_APPRVL_DT"
    Public Const OWNR_APPRVL_AMNT_NC As String = "OWNR_APPRVL_AMNT_NC"
    Public Const LSS_CD As String = "LSS_CD"
    Public Const EQPMNT_TYP_CD As String = "EQPMNT_TYP_CD"
    Public Const EQPMNT_CD_CD As String = "EQPMNT_CD_CD"
    Public Const EQPMNT_SZ_CD As String = "EQPMNT_SZ_CD"
    Public Const EQPMNT_STTS_CD As String = "EQPMNT_STTS_CD"
    Public Const CSTMR_CD As String = "CSTMR_CD"
    Public Const SRVC_TX_RT As String = "SRVC_TX_RT"
    Public Const DPT_CD As String = "DPT_CD"
    Public Const BS_CRRNCY_CD As String = "BS_CRRNCY_CD"
    Public Const DPP_CRRNCY_CD As String = "DPP_CRRNCY_CD"
    Public Const MSR_CD As String = "MSR_CD"
    Public Const UNT_CD As String = "UNT_CD"


    'Table Name: V_REPAIR_ESTIMATE_DETAIL
    Public Const RPR_CD As String = "RPR_CD"
    Public Const DMG_CD As String = "DMG_CD"
    Public Const CMPNNT_CD As String = "CMPNNT_CD"
    Public Const MTRL_CD As String = "MTRL_CD"
    Public Const RSPNSBLTY_CD As String = "RSPNSBLTY_CD"
    Public Const TX_RL_CD As String = "TX_RL_CD"
    Public Const RPR_DSCRPTN_VC As String = "RPR_DSCRPTN_VC"
    Public Const DMG_DSCRPTN_VC As String = "DMG_DSCRPTN_VC"
    Public Const CMPNNT_DSCRPTN_VC As String = "CMPNNT_DSCRPTN_VC"

    'Table Name: REPORT_SUMMARY_DETAIL
    Public Const USR_LH As String = "USR_LH"
    Public Const INSRR_LH As String = "INSRR_LH"
    Public Const OWNR_LH As String = "OWNR_LH"
    Public Const DPT_LH As String = "DPT_LH"
    Public Const OTHR_LH As String = "OTHR_LH"
    Public Const DLTN_LH As String = "DLTN_LH"
    Public Const USR_LHC As String = "USR_LHC"
    Public Const INSRR_LHC As String = "INSRR_LHC"
    Public Const OWNR_LHC As String = "OWNR_LHC"
    Public Const DPT_LHC As String = "DPT_LHC"
    Public Const OTHR_LHC As String = "OTHR_LHC"
    Public Const DLTN_LHC As String = "DLTN_LHC"
    Public Const USR_MC As String = "USR_MC"
    Public Const INSRR_MC As String = "INSRR_MC"
    Public Const OWNR_MC As String = "OWNR_MC"
    Public Const DPT_MC As String = "DPT_MC"
    Public Const OTHR_MC As String = "OTHR_MC"
    Public Const DLTN_MC As String = "DLTN_MC"
    Public Const USR_TX As String = "USR_TX"
    Public Const INSRR_TX As String = "INSRR_TX"
    Public Const OWNR_TX As String = "OWNR_TX"
    Public Const DPT_TX As String = "DPT_TX"
    Public Const OTHR_TX As String = "OTHR_TX"
    Public Const DLTN_TX As String = "DLTN_TX"
    Public Const USR_TTL As String = "USR_TTL"
    Public Const INSRR_TTL As String = "INSRR_TTL"
    Public Const OWNR_TTL As String = "OWNR_TTL"
    Public Const DPT_TTL As String = "DPT_TTL"
    Public Const OTHR_TTL As String = "OTHR_TTL"
    Public Const DLTN_TTL As String = "DLTN_TTL"
    Public Const TTL_EST_CST As String = "TTL_EST_CST"
    Public Const TTL_CLN_CST As String = "TTL_CLN_CST"
    Public Const TTL_LBR_CST As String = "TTL_LBR_CST"
    Public Const TTL_SRVC_CST As String = "TTL_SRVC_CST"
    Public Const TTL_EST_SRVC_CST As String = "TTL_EST_SRVC_CST"
    'Table Name: SUMMARY_DETAIL
    Public Const USR_SMMRY As String = "USR_SMMRY"
    Public Const INSR_SMMRY As String = "INSR_SMMRY"
    Public Const OWNR_SMMRY As String = "OWNR_SMMRY"
    Public Const DPT_SMMRY As String = "DPT_SMMRY"
    Public Const OTHRS_SMMRY As String = "OTHRS_SMMRY"
    Public Const DLTNS_SMMRY As String = "DLTNS_SMMRY"
    Public Const SMMRY_ID As String = "SMMRY_ID"





#End Region

End Class

#End Region

