Public Class EnquiryData

#Region "Declaration Part.."
    'Data Tables..
    Public Const _V_PRODUCT As String = "V_PRODUCT"
    Public Const _V_CUSTOMER As String = "V_CUSTOMER"
    Public Const _V_ENQUIRY_PRODUCT_CLEANING_RATE As String = "V_ENQUIRY_PRODUCT_CLEANING_RATE"
    Public Const _V_ENQUIRY_CUSTOMER_CLEANING_RATE As String = "V_ENQUIRY_CUSTOMER_CLEANING_RATE"
    Public Const _V_ENQUIRY_CUSTOMER_CHARGE As String = "V_ENQUIRY_CUSTOMER_CHARGE"
    Public Const _V_CUSTOMER_RENTAL As String = "V_CUSTOMER_RENTAL"
    Public Const _V_CUSTOMER_TRANSPORTATION As String = "V_CUSTOMER_TRANSPORTATION"
    Public Const _V_ROUTE As String = "V_ROUTE"
    Public Const _V_TRANSPORTER_ROUTE_DETAIL As String = "V_TRANSPORTER_ROUTE_DETAIL"
    Public Const _V_ENQUIRY_CUSTOMER_CLEANINGSLAB As String = "V_ENQUIRY_CUSTOMER_CLEANINGSLAB"
    'Data Columns..

    'Table Name: V_PRODUCT
    Public Const PRDCT_ID As String = "PRDCT_ID"
    Public Const PRDCT_CD As String = "PRDCT_CD"
    Public Const PRDCT_DSCRPTN_VC As String = "PRDCT_DSCRPTN_VC"
    Public Const CHMCL_NM As String = "CHMCL_NM"
    Public Const IMO_CLSS As String = "IMO_CLSS"
    Public Const UN_NO As String = "UN_NO"
    Public Const CLSSFCTN_ID As String = "CLSSFCTN_ID"
    Public Const PRODUCT_CLASSIFICATION As String = "PRODUCT_CLASSIFICATION"
    Public Const GRP_CLSSFCTN_ID As String = "GRP_CLSSFCTN_ID"
    Public Const GROUP_CLASSIFICATION As String = "GROUP_CLASSIFICATION"
    Public Const RMRKS_VC As String = "RMRKS_VC"
    Public Const CLNNG_TTL_AMNT_NC As String = "CLNNG_TTL_AMNT_NC"
    Public Const CLNBL_BT As String = "CLNBL_BT"
    Public Const CRTD_BY As String = "CRTD_BY"
    Public Const CRTD_DT As String = "CRTD_DT"
    Public Const MDFD_BY As String = "MDFD_BY"
    Public Const MDFD_DT As String = "MDFD_DT"
    Public Const ACTV_BT As String = "ACTV_BT"
    Public Const DPT_ID As String = "DPT_ID"
    Public Const CHECKED As String = "CHECKED"
    Public Const TTL_AMNT_NC As String = "TTL_AMNT_NC"
    Public Const CLNBL As String = "CLNBL"
    'Table Name: V_CUSTOMER
    Public Const CSTMR_ID As String = "CSTMR_ID"
    Public Const CSTMR_CD As String = "CSTMR_CD"
    Public Const CSTMR_NAM As String = "CSTMR_NAM"
    Public Const CSTMR_CRRNCY_ID As String = "CSTMR_CRRNCY_ID"
    Public Const CSTMR_CRRNCY_CD As String = "CSTMR_CRRNCY_CD"
    Public Const CNVRT_TO_CRRNCY_ID As String = "CNVRT_TO_CRRNCY_ID"
    Public Const CNVRT_TO_CRRNCY_CD As String = "CNVRT_TO_CRRNCY_CD"
    Public Const BLLNG_TYP_ID As String = "BLLNG_TYP_ID"
    Public Const BLLNG_TYP_CD As String = "BLLNG_TYP_CD"
    Public Const CNTCT_PRSN_NAM As String = "CNTCT_PRSN_NAM"
    Public Const CNTCT_ADDRSS As String = "CNTCT_ADDRSS"
    Public Const BLLNG_ADDRSS As String = "BLLNG_ADDRSS"
    Public Const ZP_CD As String = "ZP_CD"
    Public Const PHN_NO As String = "PHN_NO"
    Public Const FX_NO As String = "FX_NO"
    Public Const RPRTNG_EML_ID As String = "RPRTNG_EML_ID"
    Public Const INVCNG_EML_ID As String = "INVCNG_EML_ID"
    Public Const RPR_TCH_EML_ID As String = "RPR_TCH_EML_ID"
    Public Const BLK_EML_FRMT_ID As String = "BLK_EML_FRMT_ID"
    Public Const BLK_EML_FRMT_CD As String = "BLK_EML_FRMT_CD"
    Public Const HYDR_AMNT_NC As String = "HYDR_AMNT_NC"
    Public Const PNMTC_AMNT_NC As String = "PNMTC_AMNT_NC"
    Public Const LBR_RT_PR_HR_NC As String = "LBR_RT_PR_HR_NC"
    Public Const LK_TST_RT_NC As String = "LK_TST_RT_NC"
    Public Const SRVY_ONHR_OFFHR_RT_NC As String = "SRVY_ONHR_OFFHR_RT_NC"
    Public Const PRDC_TST_TYP_ID As String = "PRDC_TST_TYP_ID"
    Public Const PRDC_TST_TYP_CD As String = "PRDC_TST_TYP_CD"
    Public Const VLDTY_PRD_TST_YRS As String = "VLDTY_PRD_TST_YRS"
    Public Const MIN_HTNG_RT_NC As String = "MIN_HTNG_RT_NC"
    Public Const MIN_HTNG_PRD_NC As String = "MIN_HTNG_PRD_NC"
    Public Const HRLY_CHRG_NC As String = "HRLY_CHRG_NC"
    Public Const CHK_DGT_VLDTN_BT As String = "CHK_DGT_VLDTN_BT"
    Public Const TRNSPRTTN_BT As String = "TRNSPRTTN_BT"
    Public Const RNTL_BT As String = "RNTL_BT"
    Public Const DPT_CD As String = "DPT_CD"

    'Table Name: V_ENQUIRY_PRODUCT_CLEANING_RATE
    Public Const CLNNG_AMNT_NC As String = "CLNNG_AMNT_NC"
    Public Const SCRBBNG_AMNT_NC As String = "SCRBBNG_AMNT_NC"
    Public Const HTNG_AMNT_NC As String = "HTNG_AMNT_NC"
    Public Const HNDLNG_AMNT_NC As String = "HNDLNG_AMNT_NC"
    Public Const DSPSNG_AMNT_NC As String = "DSPSNG_AMNT_NC"
    Public Const OTHR_AMNT_NC As String = "OTHR_AMNT_NC"
    Public Const DPT_LCL_CRRNCY As String = "DPT_LCL_CRRNCY"

    'Table Name: V_ENQUIRY_CUSTOMER_CLEANING_RATE
    Public Const PRDCT_CSTMR_CD As String = "PRDCT_CSTMR_CD"
    Public Const PRDCT_CSTMR_ID As String = "PRDCT_CSTMR_ID"
    Public Const PRDCT_CSTMR_NAM As String = "PRDCT_CSTMR_NAM"
    Public Const CSTMR_CRRNCY As String = "CSTMR_CRRNCY"

    'Table Name: V_ENQUIRY_CUSTOMER_CHARGE
    Public Const EQPMNT_CD_ID As String = "EQPMNT_CD_ID"
    Public Const EQPMNT_TYP_ID As String = "EQPMNT_TYP_ID"
    Public Const HNDLNG_IN_CHRG_NC As String = "HNDLNG_IN_CHRG_NC"
    Public Const HNDLNG_OUT_CHRG_NC As String = "HNDLNG_OUT_CHRG_NC"
    Public Const UP_TO_DYS As String = "UP_TO_DYS"
    Public Const STRG_CHRG_NC As String = "STRG_CHRG_NC"
    Public Const EQPMNT_CD_CD As String = "EQPMNT_CD_CD"
    Public Const EQPMNT_TYP_CD As String = "EQPMNT_TYP_CD"

    'Table Name: V_CUSTOMER_RENTAL
    Public Const CSTMR_RNTL_ID As String = "CSTMR_RNTL_ID"
    Public Const SPPLR_ID As String = "SPPLR_ID"
    Public Const CNTRCT_RFRNC_NO As String = "CNTRCT_RFRNC_NO"
    Public Const CNTRCT_STRT_DT As String = "CNTRCT_STRT_DT"
    Public Const CNTRCT_END_DT As String = "CNTRCT_END_DT"
    Public Const RNTL_PR_DY As String = "RNTL_PR_DY"
    Public Const SPPLR_RMRKS_VC As String = "SPPLR_RMRKS_VC"
    Public Const HNDLNG_OT As String = "HNDLNG_OT"
    Public Const HNDLNG_IN As String = "HNDLNG_IN"
    Public Const ON_HR_SRVY As String = "ON_HR_SRVY"
    Public Const OFF_HR_SRVY As String = "OFF_HR_SRVY"
    Public Const MN_TNR_DY As String = "MN_TNR_DY"

    'Data Columns..

    'Table Name: V_CUSTOMER_TRANSPORTATION
    Public Const CSTMR_TRNSPRTTN_ID As String = "CSTMR_TRNSPRTTN_ID"
    Public Const RT_ID As String = "RT_ID"
    Public Const RT_CD As String = "RT_CD"
    Public Const RT_DSCRPTN_VC As String = "RT_DSCRPTN_VC"
    Public Const PCK_UP_LCTN_CD As String = "PCK_UP_LCTN_CD"
    Public Const PCK_UP_LCTN_DSCRPTN_VC As String = "PCK_UP_LCTN_DSCRPTN_VC"
    Public Const DRP_OFF_LCTN_CD As String = "DRP_OFF_LCTN_CD"
    Public Const DRP_OFF_LCTN_DSCRPTN_VC As String = "DRP_OFF_LCTN_DSCRPTN_VC"
    Public Const ACTVTY_CD As String = "ACTVTY_CD"
    Public Const ACTVTY_LCTN_CD As String = "ACTVTY_LCTN_CD"
    Public Const EMPTY_TRP_RT_NC As String = "EMPTY_TRP_RT_NC"
    Public Const FLL_TRP_RT_NC As String = "FLL_TRP_RT_NC"
    Public Const ACTVTY_LCTN_DSCRPTN_VC As String = "ACTVTY_LCTN_DSCRPTN_VC"
    Public Const ALLOW_RNTL As String = "ALLOW_RNTL"
    Public Const ALLOW_TRNSPRTTN As String = "ALLOW_TRNSPRTTN"
    Public Const ALLOW_CLNNG_SLAB As String = "ALLOW_CLNNG_SLAB"
    Public Const DPT_CRRNCY_CD As String = "DPT_CRRNCY_CD"

    'Table Name: V_ROUTE
    Public Const PCK_UP_LCTN_ID As String = "PCK_UP_LCTN_ID"
    Public Const DRP_OFF_LCTN_ID As String = "DRP_OFF_LCTN_ID"
    Public Const ACTVTY_ID As String = "ACTVTY_ID"
    Public Const ACTVTY_LCTN_ID As String = "ACTVTY_LCTN_ID"
    Public Const RPRT As String = "RPRT"

#End Region
End Class
