Public Class CleaningData
#Region "Declaration Part.."
    'Data Tables..
    Public Const _CLEANING As String = "CLEANING"
    Public Const _V_ACTIVITY_STATUS As String = "V_ACTIVITY_STATUS"
    Public Const _PRODUCT As String = "PRODUCT"
    Public Const _V_CLEANING As String = "V_CLEANING"
    Public Const _CLEANING_CHARGE As String = "CLEANING_CHARGE"
    Public Const _ACTIVITY_STATUS As String = "ACTIVITY_STATUS"
    Public Const _GATEIN As String = "GATEIN"
    Public Const _TRACKING As String = "TRACKING"
    Public Const _CLEANING_CERTIFICATE As String = "CLEANING_CERTIFICATE"
    Public Const _CLEANING_INSPECTION As String = "CLEANING_INSPECTION"
    Public Const _INVOICING_PARTY As String = "INVOICING_PARTY"
    Public Const _CUSTOMER As String = "CUSTOMER"
    Public Const _V_CUSTOMER As String = "V_CUSTOMER"
    Public Const _PRINT_CLEANING_INSPECTION As String = "PRINT_CLEANING_INSPECTION"

    'Data Columns..
    'Table Name: CLEANING
    Public Const PRDCT_DSCRPTN_VC As String = "PRDCT_DSCRPTN_VC"
    Public Const CLNNG_ID As String = "CLNNG_ID"
    Public Const CLNNG_CD As String = "CLNNG_CD"
    Public Const CSTMR_ID As String = "CSTMR_ID"
    Public Const EQPMNT_NO As String = "EQPMNT_NO"
    Public Const CLNNG_CERT_NO As String = "CLNNG_CERT_NO"
    Public Const PRDCT_ID As String = "PRDCT_ID"
    Public Const CHMCL_NM As String = "CHMCL_NM"
    Public Const CLNNG_RT As String = "CLNNG_RT"
    Public Const ORGNL_CLNNG_DT As String = "ORGNL_CLNNG_DT"
    Public Const LST_CLNNG_DT As String = "LST_CLNNG_DT"
    Public Const ORGNL_INSPCTD_DT As String = "ORGNL_INSPCTD_DT"
    Public Const LST_INSPCTD_DT As String = "LST_INSPCTD_DT"
    Public Const EQPMNT_STTS_ID As String = "EQPMNT_STTS_ID"
    Public Const CLND_FR_VCR As String = "CLND_FR_VCR"
    Public Const LCTN_OF_CLNG As String = "LCTN_OF_CLNG"
    Public Const EQPMNT_CLNNG_STTS_1 As String = "EQPMNT_CLNNG_STTS_1"
    Public Const EQPMNT_CLNNG_STTS_2 As String = "EQPMNT_CLNNG_STTS_2"
    Public Const EQPMNT_CNDTN_ID As String = "EQPMNT_CNDTN_ID"
    Public Const VLV_FTTNG_CNDTN As String = "VLV_FTTNG_CNDTN"
    Public Const MN_LID_SL_NO As String = "MN_LID_SL_NO"
    Public Const TP_SL_NO As String = "TP_SL_NO"
    Public Const BTTM_SL_NO As String = "BTTM_SL_NO"
    Public Const INVCNG_PRTY_ID As String = "INVCNG_PRTY_ID"
    Public Const CSTMR_RFRNC_NO As String = "CSTMR_RFRNC_NO"
    Public Const CLNNG_RFRNC_NO As String = "CLNNG_RFRNC_NO"
    Public Const RMRKS_VC As String = "RMRKS_VC"
    Public Const DPT_ID As String = "DPT_ID"
    Public Const GI_TRNSCTN_NO As String = "GI_TRNSCTN_NO"
    Public Const CRTD_BY As String = "CRTD_BY"
    Public Const CRTD_DT As String = "CRTD_DT"
    Public Const MDFD_BY As String = "MDFD_BY"
    Public Const MDFD_DT As String = "MDFD_DT"
    Public Const CERT_GNRTD_FLG As String = "CERT_GNRTD_FLG"
    Public Const IS_CHNG_OF_STTS As String = "IS_CHNG_OF_STTS"
    Public Const ADDTNL_CLNNG_BT As String = "ADDTNL_CLNNG_BT"
    Public Const CLNNG_INSPCTN_REF_NO As String = "CLNNG_INSPCTN_REF_NO"
    Public Const CLNNG_INSPCTN_NO As String = "CLNNG_INSPCTN_NO"

    'Table Name: V_ACTIVITY_STATUS
    Public Const ACTVTY_STTS_ID As String = "ACTVTY_STTS_ID"
    Public Const CSTMR_CD As String = "CSTMR_CD"
    Public Const CSTMR_NAM As String = "CSTMR_NAM"
    Public Const EQPMNT_TYP_ID As String = "EQPMNT_TYP_ID"
    Public Const EQPMNT_TYP_CD As String = "EQPMNT_TYP_CD"
    Public Const EQPMNT_CD_ID As String = "EQPMNT_CD_ID"
    Public Const EQPMNT_CD_CD As String = "EQPMNT_CD_CD"
    Public Const INSPCTN_DT As String = "INSPCTN_DT"
    Public Const GTN_DT As String = "GTN_DT"
    Public Const GTOT_DT As String = "GTOT_DT"
    Public Const PRDCT_CD As String = "PRDCT_CD"
    Public Const CHMCL_NAM As String = "CHMCL_NAM"
    Public Const EQPMNT_STTS_CD As String = "EQPMNT_STTS_CD"
    Public Const ACTVTY_NAM As String = "ACTVTY_NAM"
    Public Const ACTVTY_DT As String = "ACTVTY_DT"
    Public Const RMRKS_VCR As String = "RMRKS_VCR"
    Public Const ACTV_BT As String = "ACTV_BT"
    Public Const DPT_CD As String = "DPT_CD"
    Public Const DPT_NAM As String = "DPT_NAM"
    Public Const YRD_LCTN As String = "YRD_LCTN"
    Public Const FILTER_CODE As String = "FILTER_CODE"
    Public Const NEW_EQPMNT_STTS_CD As String = "NEW_EQPMNT_STTS_CD"
    Public Const NEW_ACTVTY_DT As String = "NEW_ACTVTY_DT"
    Public Const CLNNG_DT As String = "CLNNG_DT"
    Public Const CRRNCY_CD As String = "CRRNCY_CD"
    Public Const BS_CRRNCY_ID As String = "BS_CRRNCY_ID"
    Public Const CLNNG_RMRKS_VC As String = "CLNNG_RMRKS_VC"
    Public Const SCHDL_DT As String = "SCHDL_DT"

    'Table Name: V_CLEANING

    Public Const EQPMNT_STTS_DSCRPTN_VC As String = "EQPMNT_STTS_DSCRPTN_VC"
    Public Const EQPMNT_CLNNG_STTS_1_CD As String = "EQPMNT_CLNNG_STTS_1_CD"
    Public Const EQPMNT_CLNNG_STTS_2_CD As String = "EQPMNT_CLNNG_STTS_2_CD"
    Public Const EQPMNT_CNDTN_CD As String = "EQPMNT_CNDTN_CD"
    Public Const VLV_FTTNG_CNDTN_CD As String = "VLV_FTTNG_CNDTN_CD"
    Public Const INVCNG_PRTY_CD As String = "INVCNG_PRTY_CD"

    Public Const WF_ACTIVITY_ID As String = "WF_ACTIVITY_ID"
    Public Const WF_ACTIVITY_NAME As String = "WF_ACTIVITY_NAME"
    Public Const PENDING_STATUS As String = "PENDING_STATUS"
    Public Const DEFAULT_STATUS As String = "DEFAULT_STATUS"
    Public Const DEFAULT_STATUS_ID As String = "DEFAULT_STATUS_ID"
    Public Const EQUIPMENT_TYPE As String = "EQUIPMENT_TYPE"
    Public Const EQUIPMENT_CODE As String = "EQUIPMENT_CODE"

    'Table Name: CLEANING_CHARGE
    Public Const CLNNG_CHRG_ID As String = "CLNNG_CHRG_ID"
    Public Const BLLNG_FLG As String = "BLLNG_FLG"
    Public Const SLB_RT_BT As String = "SLB_RT_BT"

    'Data Columns..

    'Table Name: TRACKING
    Public Const TRCKNG_ID As String = "TRCKNG_ID"
    Public Const ACTVTY_NO As String = "ACTVTY_NO"
    Public Const ACTVTY_RMRKS As String = "ACTVTY_RMRKS"
    Public Const GI_RF_NO As String = "GI_RF_NO"
    Public Const RFRNC_NO As String = "RFRNC_NO"
    Public Const EQPMNT_INFRMTN_RMRKS_VC As String = "EQPMNT_INFRMTN_RMRKS_VC"
    Public Const ADDTNL_CLNNG_FLG As String = "ADDTNL_CLNNG_FLG"
    'View Name: V_CLEANING
    Public Const CRRNT_EQPMNT_STTS_ID As String = "CRRNT_EQPMNT_STTS_ID"

#End Region
End Class
