Public Class EquipmentInspectionData
    Public Const _EQUIPMENT_INSPECTION As String = "EQUIPMENT_INSPECTION"
    Public Const _ACTIVITY_STATUS As String = "ACTIVITY_STATUS"
    Public Const _V_EQUIPMENT_INSPECTION As String = "V_EQUIPMENT_INSPECTION"
    Public Const _TRACKING As String = "TRACKING"
    Public Const _EQUIPMENT_STATUS As String = "EQUIPMENT_STATUS"
    Public Const _CUSTOMER As String = "CUSTOMER"
    Public Const _INSPECTION_CHARGES As String = "INSPECTION_CHARGES"

    Public Const RMRKS_VC As String = "RMRKS_VC"
    Public Const CRTD_BY As String = "CRTD_BY"
    Public Const CRTD_DT As String = "CRTD_DT"
    Public Const MDFD_BY As String = "MDFD_BY"
    Public Const MDFD_DT As String = "MDFD_DT"
    Public Const ACTV_BT As String = "ACTV_BT"
    Public Const DPT_ID As String = "DPT_ID"
    Public Const CHECKED As String = "CHECKED"
    Public Const CSTMR_ID As String = "CSTMR_ID"
    Public Const CSTMR_CD As String = "CSTMR_CD"
    Public Const GI_TRNSCTN_NO As String = "GI_TRNSCTN_NO"
    Public Const CSTMR_NAM As String = "CSTMR_NAM"
    Public Const INSPCTN_CHRGS As String = "INSPCTN_CHRGS"

    'Table Name: ACTIVITY_STATUS
    Public Const ACTVTY_STTS_ID As String = "ACTVTY_STTS_ID"
    Public Const GTOT_DT As String = "GTOT_DT"
    Public Const CLNNG_DT As String = "CLNNG_DT"
    Public Const ACTVTY_ID As String = "ACTVTY_ID"
    Public Const RMRKS_VCR As String = "RMRKS_VCR"
    Public Const GI_RF_NO As String = "GI_RF_NO"
    Public Const ACTVTY_DT As String = "ACTVTY_DT"
    Public Const ACTVTY_NAM As String = "ACTVTY_NAM"
    Public Const RFRNC_NO As String = "RFRNC_NO"
    Public Const ACTVTY_RMRKS As String = "ACTVTY_RMRKS"
    Public Const INSPCTN_DT As String = "INSPCTN_DT"

    'Table Name : INSPECTION_CHARGES
    Public Const INSPCTN_CHRG_ID As String = "INSPCTN_CHRG_ID"
    Public Const CSTMR_AGNT_ID As String = "CSTMR_AGNT_ID"
    Public Const INSPCTN_CHRG As String = "INSPCTN_CHRG"
    Public Const BLLNG_FLG As String = "BLLNG_FLG"
    Public Const DRFT_INVC_NO As String = "DRFT_INVC_NO"
    Public Const FNL_INVC_NO As String = "FNL_INVC_NO"

    'Table Name: EQUIPMENT_INSPECTION
    Public Const EQPMNT_INSPCTN_ID As String = "EQPMNT_INSPCTN_ID"
    Public Const EQPMNT_TYP_ID As String = "EQPMNT_TYP_ID"
    Public Const EQPMNT_TYP_CD As String = "EQPMNT_TYP_CD"
    Public Const EQPMNT_CD_ID As String = "EQPMNT_CD_ID"
    Public Const EQPMNT_CD_CD As String = "EQPMNT_CD_CD"
    Public Const EQPMNT_STTS_ID As String = "EQPMNT_STTS_ID"
    Public Const EQPMNT_STTS_CD As String = "EQPMNT_STTS_CD"
    Public Const EQPMNT_NO As String = "EQPMNT_NO"
    Public Const YRD_LCTN As String = "YRD_LCTN"
    Public Const GTN_DT As String = "GTN_DT"
    Public Const EIR_NO As String = "EIR_NO"
    Public Const EQPMNT_STTS_DSCRPTN_VC As String = "EQPMNT_STTS_DSCRPTN_VC"
    Public Const BLL_ID As String = "BLL_ID"
    Public Const AGNT_ID As String = "AGNT_ID"
    Public Const AGNT_CD As String = "AGNT_CD"
    Public Const GRD_ID As String = "GRD_ID"
    Public Const GRD_CD As String = "GRD_CD"
    Public Const INSPCTD_BY As String = "INSPCTD_BY"
    Public Const INSPCTD_DT As String = "INSPCTD_DT"

End Class
