#Region "GateOutData"
Public Class GateOutData


#Region "Declaration Part.."
    'Data Tables..
    Public Const _GATEOUT_RET As String = "GATEOUT_RET"
    Public Const _HANDLING_CHARGE As String = "HANDLING_CHARGE"
    Public Const _STORAGE_CHARGE As String = "STORAGE_CHARGE"

    Public Const _TRACKING As String = "TRACKING"
    Public Const _CUSTOMER_RATE As String = "CUSTOMER_RATE"
    Public Const _GATEIN As String = "GATEIN"
    Public Const _EQUIPMENT_STATUS As String = "EQUIPMENT_STATUS"

    Public Const _V_GATEOUT_DETAIL As String = "V_GATEOUT_DETAIL"
    Public Const _V_GATEOUT As String = "V_GATEOUT"
    Public Const _GATEOUT As String = "GATEOUT"
    Public Const _GATEOUT_DETAIL As String = "GATEOUT_DETAIL"
    Public Const _ACTIVITY_STATUS As String = "ACTIVITY_STATUS"
    Public Const _V_GATEIN_DETAIL As String = "V_GATEIN_DETAIL"
    Public Const _CUSTOMER As String = "CUSTOMER"
    Public Const _V_CUSTOMER_CHARGE_DETAIL As String = "V_CUSTOMER_CHARGE_DETAIL"
    Public Const _RENTAL_ENTRY As String = "RENTAL_ENTRY"
    Public Const _RENTAL_GATEOUT As String = "RENTAL_GATEOUT"
    Public Const _V_ACTIVITY_STATUS As String = "V_ACTIVITY_STATUS"
    Public Const _RENTAL_CHARGE As String = "RENTAL_CHARGE"
    Public Const _CUSTOMER_RENTAL As String = "CUSTOMER_RENTAL"
    Public Const _V_RENTAL_ENTRY As String = "V_RENTAL_ENTRY"

    Public Const _EQUIPMENT_CODE As String = "EQUIPMENT_CODE"
    Public Const _ATTACHMENT As String = "ATTACHMENT"
    Public Const _V_ATTACHMENT As String = "V_ATTACHMENT"
    Public Const _EQUIPMENT_INFORMATION As String = "EQUIPMENT_INFORMATION"
    'Data Columns..
    Public Const EQPMNT_CD_DSCRPTN_VC As String = "EQPMNT_CD_DSCRPTN_VC"
    'Table Name: EQUIPMENT_ACTIVITY
    Public Const EQPMNT_NO As String = "EQPMNT_NO"
    Public Const TRNSPRTR_CD As String = "TRNSPRTR_CD"
    Public Const ACTVTY As String = "ACTVTY"
    Public Const ACTVTY_DT As String = "ACTVTY_DT"
    Public Const CSTMR_ID As String = "CSTMR_ID"
    Public Const DPT_ID As String = "DPT_ID"
    Public Const GTN_ID As String = "GTN_ID"
    Public Const EIR_DT As String = "EIR_DT"

    'Table Name: GATEOUT
    Public Const GTOT_BIN As String = "GTOT_BIN"
    Public Const TRNSMSSN_NO As String = "TRNSMSSN_NO"
    Public Const SNT_DT As String = "SNT_DT"
    Public Const GTOT_TRNSXN As String = "GTOT_TRNSXN"
    Public Const EQPMNT_TYP_ID As String = "EQPMNT_TYP_ID"
    Public Const EQPMNT_CD_ID As String = "EQPMNT_CD_ID"
    Public Const GTOT_CNDTN As String = "GTOT_CNDTN"
    Public Const LSS_ID As String = "LSS_ID"
    Public Const MNFCTR_DT As String = "MNFCTR_DT"
    Public Const MTRL_ID As String = "MTRL_ID"
    Public Const WGHT As String = "WGHT"
    Public Const MSR_ID As String = "MSR_ID"
    Public Const UNT_ID As String = "UNT_ID"
    Public Const ACEP_CD As String = "ACEP_CD"
    Public Const CNTRY_ID As String = "CNTRY_ID"
    Public Const LIC_STT As String = "LIC_STT"
    Public Const LIC_REG As String = "LIC_REG"
    Public Const LIC_EXPR As String = "LIC_EXPR"
    Public Const TRCKR_CD As String = "TRCKR_CD"
    Public Const NT_1_VC As String = "NT_1_VC"
    Public Const NT_2_VC As String = "NT_2_VC"
    Public Const NT_3_VC As String = "NT_3_VC"
    Public Const LDD_STTS_CD As String = "LDD_STTS_CD"
    Public Const LST_OH_LOC As String = "LST_OH_LOC"
    Public Const LST_OH_DT As String = "LST_OH_DT"
    Public Const SL_PRTY_1_ID As String = "SL_PRTY_1_ID"
    Public Const SL_NMBR_1 As String = "SL_NMBR_1"
    Public Const SL_PRTY_2_ID As String = "SL_PRTY_2_ID"
    Public Const SL_NMBR_2 As String = "SL_NMBR_2"
    Public Const SL_PRTY_3_ID As String = "SL_PRTY_3_ID"
    Public Const SL_NMBR_3 As String = "SL_NMBR_3"
    Public Const SL_PRTY_4_ID As String = "SL_PRTY_4_ID"
    Public Const SL_NMBR_4 As String = "SL_NMBR_4"
    Public Const PRT_FNC_CD As String = "PRT_FNC_CD"
    Public Const PRT_NM As String = "PRT_NM"
    Public Const VSSL_NM As String = "VSSL_NM"
    Public Const VYG_NO As String = "VYG_NO"
    Public Const HAZ_MTL_CD As String = "HAZ_MTL_CD"
    Public Const HAZ_MATL_DSC As String = "HAZ_MATL_DSC"
    Public Const SHPPR_NAM As String = "SHPPR_NAM"
    Public Const RL_ID_VC As String = "RL_ID_VC"
    Public Const RL_RMP_LOC As String = "RL_RMP_LOC"
    Public Const VSSL_CD As String = "VSSL_CD"
    Public Const LOC_DNT As String = "LOC_DNT"
    Public Const PRT_LC_CD As String = "PRT_LC_CD"
    Public Const EQPMNT_STTS_ID As String = "EQPMNT_STTS_ID"
    Public Const CRTD_BY As String = "CRTD_BY"
    Public Const ACTV_BT As String = "ACTV_BT"
    Public Const YRD_LOC As String = "YRD_LOC"
    Public Const COUNT As String = "COUNT"
    Public Const GRD_ID As String = "GRD_ID"
    Public Const GRD_CD As String = "GRD_CD"
    Public Const RMRKS_VC As String = "RMRKS_VC"
    Public Const VHCL_NO As String = "VHCL_NO"
    Public Const AGENT_ID As String = "AGENT_ID"

    Public Const SL_NO As String = "SL_NO"
    Public Const AUTH_NO As String = "AUTH_NO"




    'Table Name: GATEOUT_RET
    Public Const GO_SNO As String = "GO_SNO"
    Public Const GO_TRANSMISSION_NO As String = "GO_TRANSMISSION_NO"
    Public Const GO_COMPLETE As String = "GO_COMPLETE"
    Public Const GO_SENT_EIR As String = "GO_SENT_EIR"
    Public Const GO_SENT_DATE As String = "GO_SENT_DATE"
    Public Const GO_REC_EIR As String = "GO_REC_EIR"
    Public Const GO_REC_DATE As String = "GO_REC_DATE"
    Public Const GO_REC_ADDR As String = "GO_REC_ADDR"
    Public Const GO_REC_TYPE As String = "GO_REC_TYPE"
    Public Const GO_EXPORTED As String = "GO_EXPORTED"
    Public Const GO_EXPOR_DATE As String = "GO_EXPOR_DATE"
    Public Const GO_IMPORTED As String = "GO_IMPORTED"
    Public Const GO_IMPOR_DATE As String = "GO_IMPOR_DATE"
    Public Const GO_TRNSXN As String = "GO_TRNSXN"
    Public Const GO_ADVICE As String = "GO_ADVICE"
    Public Const GO_UNIT_NBR As String = "GO_UNIT_NBR"
    Public Const GO_EQUIP_TYPE As String = "GO_EQUIP_TYPE"
    Public Const GO_EQUIP_DESC As String = "GO_EQUIP_DESC"
    Public Const GO_EQUIP_CODE As String = "GO_EQUIP_CODE"
    Public Const GO_CONDITION As String = "GO_CONDITION"
    Public Const GO_COMP_ID_A As String = "GO_COMP_ID_A"
    Public Const GO_COMP_ID_N As String = "GO_COMP_ID_N"
    Public Const GO_COMP_ID_C As String = "GO_COMP_ID_C"
    Public Const GO_COMP_TYPE As String = "GO_COMP_TYPE"
    Public Const GO_COMP_DESC As String = "GO_COMP_DESC"
    Public Const GO_COMP_CODE As String = "GO_COMP_CODE"
    Public Const GO_EIR_DATE As String = "GO_EIR_DATE"
    Public Const GO_EIR_TIME As String = "GO_EIR_TIME"
    Public Const GO_REFERENCE As String = "GO_REFERENCE"
    Public Const GO_MANU_DATE As String = "GO_MANU_DATE"
    Public Const GO_MATERIAL As String = "GO_MATERIAL"
    Public Const GO_WEIGHT As String = "GO_WEIGHT"
    Public Const GO_MEASURE As String = "GO_MEASURE"
    Public Const GO_UNITS As String = "GO_UNITS"
    Public Const GO_CSC_REEXAM As String = "GO_CSC_REEXAM"
    Public Const GO_COUNTRY As String = "GO_COUNTRY"
    Public Const GO_LIC_STATE As String = "GO_LIC_STATE"
    Public Const GO_LIC_REG As String = "GO_LIC_REG"
    Public Const GO_LIC_EXPIRE As String = "GO_LIC_EXPIRE"
    Public Const GO_LSR_OWNER As String = "GO_LSR_OWNER"
    Public Const GO_SEND_EDI_1 As String = "GO_SEND_EDI_1"
    Public Const GO_SSL_LSE As String = "GO_SSL_LSE"
    Public Const GO_SEND_EDI_2 As String = "GO_SEND_EDI_2"
    Public Const GO_HAULIER As String = "GO_HAULIER"
    Public Const GO_SEND_EDI_3 As String = "GO_SEND_EDI_3"
    Public Const GO_DPT_TRM As String = "GO_DPT_TRM"
    Public Const GO_SEND_EDI_4 As String = "GO_SEND_EDI_4"
    Public Const GO_OTHERS_1 As String = "GO_OTHERS_1"
    Public Const GO_OTHERS_2 As String = "GO_OTHERS_2"
    Public Const GO_OTHERS_3 As String = "GO_OTHERS_3"
    Public Const GO_OTHERS_4 As String = "GO_OTHERS_4"
    Public Const GO_NOTE_1 As String = "GO_NOTE_1"
    Public Const GO_NOTE_2 As String = "GO_NOTE_2"
    Public Const GO_LOAD As String = "GO_LOAD"
    Public Const GO_FHWA As String = "GO_FHWA"
    Public Const GO_LAST_OH_LOC As String = "GO_LAST_OH_LOC"
    Public Const GO_LAST_OH_DATE As String = "GO_LAST_OH_DATE"
    Public Const GO_SENDER As String = "GO_SENDER"
    Public Const GO_ATTENTION As String = "GO_ATTENTION"
    Public Const GO_REVISION As String = "GO_REVISION"
    Public Const GO_SEND_EDI_5 As String = "GO_SEND_EDI_5"
    Public Const GO_SEND_EDI_6 As String = "GO_SEND_EDI_6"
    Public Const GO_SEND_EDI_7 As String = "GO_SEND_EDI_7"
    Public Const GO_SEND_EDI_8 As String = "GO_SEND_EDI_8"
    Public Const GO_SEAL_PARTY_1 As String = "GO_SEAL_PARTY_1"
    Public Const GO_SEAL_NUMBER_1 As String = "GO_SEAL_NUMBER_1"
    Public Const GO_SEAL_PARTY_2 As String = "GO_SEAL_PARTY_2"
    Public Const GO_SEAL_NUMBER_2 As String = "GO_SEAL_NUMBER_2"
    Public Const GO_SEAL_PARTY_3 As String = "GO_SEAL_PARTY_3"
    Public Const GO_SEAL_NUMBER_3 As String = "GO_SEAL_NUMBER_3"
    Public Const GO_SEAL_PARTY_4 As String = "GO_SEAL_PARTY_4"
    Public Const GO_SEAL_NUMBER_4 As String = "GO_SEAL_NUMBER_4"
    Public Const GO_PORT_FUNC_CODE As String = "GO_PORT_FUNC_CODE"
    Public Const GO_PORT_NAME As String = "GO_PORT_NAME"
    Public Const GO_VESSEL_NAME As String = "GO_VESSEL_NAME"
    Public Const GO_VOYAGE_NUM As String = "GO_VOYAGE_NUM"
    Public Const GO_HAZ_MAT_CODE As String = "GO_HAZ_MAT_CODE"
    Public Const GO_HAZ_MAT_DESC As String = "GO_HAZ_MAT_DESC"
    Public Const GO_NOTE_3 As String = "GO_NOTE_3"
    Public Const GO_NOTE_4 As String = "GO_NOTE_4"
    Public Const GO_NOTE_5 As String = "GO_NOTE_5"
    Public Const GO_COMP_ID_A_2 As String = "GO_COMP_ID_A_2"
    Public Const GO_COMP_ID_N_2 As String = "GO_COMP_ID_N_2"
    Public Const GO_COMP_ID_C_2 As String = "GO_COMP_ID_C_2"
    Public Const GO_COMP_TYPE_2 As String = "GO_COMP_TYPE_2"
    Public Const GO_COMP_CODE_2 As String = "GO_COMP_CODE_2"
    Public Const GO_COMP_DESC_2 As String = "GO_COMP_DESC_2"
    Public Const GO_SHIPPER As String = "GO_SHIPPER"
    Public Const GO_DRAY_ORDER As String = "GO_DRAY_ORDER"
    Public Const GO_RAIL_ID As String = "GO_RAIL_ID"
    Public Const GO_RAIL_RAMP As String = "GO_RAIL_RAMP"
    Public Const GO_VESSEL_CODE As String = "GO_VESSEL_CODE"
    Public Const GO_WGHT_CERT_1 As String = "GO_WGHT_CERT_1"
    Public Const GO_WGHT_CERT_2 As String = "GO_WGHT_CERT_2"
    Public Const GO_WGHT_CERT_3 As String = "GO_WGHT_CERT_3"
    Public Const GO_SEA_RAIL As String = "GO_SEA_RAIL"
    Public Const GO_BILL_LADING As String = "GO_BILL_LADING"
    Public Const GO_LOC_IDENT As String = "GO_LOC_IDENT"
    Public Const GO_PORT_LOC_QUAL As String = "GO_PORT_LOC_QUAL"
    Public Const GO_STATUS As String = "GO_STATUS"
    Public Const GO_PICK_DATE As String = "GO_PICK_DATE"
    Public Const GO_ERRSTATUS As String = "GO_ERRSTATUS"
    Public Const GO_USERNAME As String = "GO_USERNAME"
    Public Const GO_LIVE_STATUS As String = "GO_LIVE_STATUS"
    Public Const GO_YARD_LOC As String = "GO_YARD_LOC"
    Public Const GO_MODE_PAYMENT As String = "GO_MODE_PAYMENT"
    Public Const GO_BILLING_TYPE As String = "GO_BILLING_TYPE"

    'Table Name: HANDLING_CHARGE
    Public Const HNDLNG_CHRG_ID As String = "HNDLNG_CHRG_ID"
    Public Const CST_TYP As String = "CST_TYP"
    Public Const RFRNC_EIR_NO_1 As String = "RFRNC_EIR_NO_1"
    Public Const RFRNC_EIR_NO_2 As String = "RFRNC_EIR_NO_2"
    Public Const FRM_BLLNG_DT As String = "FRM_BLLNG_DT"
    Public Const TO_BLLNG_DT As String = "TO_BLLNG_DT"
    Public Const FR_DYS As String = "FR_DYS"
    Public Const NO_OF_DYS As String = "NO_OF_DYS"
    Public Const HNDLNG_CST_NC As String = "HNDLNG_CST_NC"
    Public Const HNDLNG_TX_RT_NC As String = "HNDLNG_TX_RT_NC"
    Public Const TTL_CSTS_NC As String = "TTL_CSTS_NC"
    Public Const BLLNG_FLG As String = "BLLNG_FLG"
    Public Const IS_GT_OT_FLG As String = "IS_GT_OT_FLG"
    Public Const YRD_LCTN As String = "YRD_LCTN"
    Public Const MD_PYMNT As String = "MD_PYMNT"
    Public Const BLLNG_TYP_CD As String = "BLLNG_TYP_CD"

    Public Const GTN_DTL_ID As String = "GTN_DTL_ID"
    Public Const GRSS_WGHT_NC As String = "GRSS_WGHT_NC"
    Public Const TR_WGHT_NC As String = "TR_WGHT_NC"
    Public Const LOD_STTS_CD As String = "LOD_STTS_CD"
    Public Const PRT_NO As String = "PRT_NO"
    Public Const MORE_INFO_BIT As String = "MORE_INFO_BIT"

    'Table Name: STORAGE_CHARGE
    Public Const STRG_CHRG_ID As String = "STRG_CHRG_ID"
    Public Const STRG_CST_NC As String = "STRG_CST_NC"
    Public Const STRG_TX_RT_NC As String = "STRG_TX_RT_NC"
    Public Const STRG_CNTN_FLG As String = "STRG_CNTN_FLG"
    Public Const IS_LT_FLG As String = "IS_LT_FLG"
    Public Const BLLNG_TLL_DT As String = "BLLNG_TLL_DT"
    Public Const MODE_PYMNT As String = "MODE_PYMNT"

    'Table Name: V_GATEOUT
    Public Const EQPMNT_CD_CD As String = "EQPMNT_CD_CD"
    Public Const EQPMNT_TYP_CD As String = "EQPMNT_TYP_CD"
    Public Const LSS_CD As String = "LSS_CD"
    Public Const MTRL_CD As String = "MTRL_CD"
    Public Const MSR_CD As String = "MSR_CD"
    Public Const UNT_CD As String = "UNT_CD"
    Public Const CNTRY_CD As String = "CNTRY_CD"
    Public Const CSTMR_CD As String = "CSTMR_CD"
    Public Const DPT_CD As String = "DPT_CD"
    Public Const SL_PRTY_1_CD As String = "SL_PRTY_1_CD"
    Public Const SL_PRTY_2_CD As String = "SL_PRTY_2_CD"
    Public Const SL_PRTY_3_CD As String = "SL_PRTY_3_CD"
    Public Const EQPMNT_STTS_CD As String = "EQPMNT_STTS_CD"
    Public Const SL_PRTY_4_CD As String = "SL_PRTY_4_CD"
    Public Const EQPMNT_STTS_DSCRPTN_VC As String = "EQPMNT_STTS_DSCRPTN_VC"
    Public Const CHECKED As String = "CHECKED"
    Public Const BLLNG_TYP As String = "BLLNG_TYP"

    'Table Name: TRACKING
    Public Const TRCKNG_ID As String = "TRCKNG_ID"
    Public Const RFRNC_NO As String = "RFRNC_NO"
    Public Const PCKP_STTS_VC As String = "PCKP_STTS_VC"
    Public Const PCKP_DT As String = "PCKP_DT"
    Public Const RSND_BT As String = "RSND_BT"
    Public Const ACTVTY_NAM As String = "ACTVTY_NAM"
    Public Const HNDLNG_IN_CHRG_NC As String = "HNDLNG_IN_CHRG_NC"
    Public Const HNDLNG_OUT_CHRG_NC As String = "HNDLNG_OUT_CHRG_NC"
    Public Const STRG_CHRGS_PR_DY_NC As String = "STRG_CHRGS_PR_DY_NC"

    Public Const GTN_DT As String = "GTN_DT"
    Public Const GTN_BIN As String = "GTN_BIN"
    Public Const CSTMR_NAM As String = "CSTMR_NAM"

    Public Const GTOT_ID As String = "GTOT_ID"
    Public Const GTOT_CD As String = "GTOT_CD"
    Public Const PRDCT_ID As String = "PRDCT_ID"
    Public Const PRDCT_CD As String = "PRDCT_CD"
    Public Const GTOT_BT As String = "GTOT_BT"
    Public Const GTOT_DT As String = "GTOT_DT"
    Public Const GTOT_TM As String = "GTOT_TM"
    Public Const EIR_NO As String = "EIR_NO"
    Public Const GI_TRNSCTN_NO As String = "GI_TRNSCTN_NO"
    Public Const CRTD_DT As String = "CRTD_DT"
    Public Const MDFD_BY As String = "MDFD_BY"
    Public Const MDFD_DT As String = "MDFD_DT"
    Public Const HTNG_BT As String = "HTNG_BT"
    Public Const GTOT_DTL_ID As String = "GTOT_DTL_ID"
    Public Const ACTVTY_STTS_ID As String = "ACTVTY_STTS_ID"
    Public Const CLNNG_DT As String = "CLNNG_DT"
    Public Const ACTVTY_ID As String = "ACTVTY_ID"
    Public Const RMRKS_VCR As String = "RMRKS_VCR"
    Public Const ACTVTY_NO As String = "ACTVTY_NO"
    Public Const ACTVTY_RMRKS As String = "ACTVTY_RMRKS"
    Public Const CSTMR_CHRG_DTL_ID As String = "CSTMR_CHRG_DTL_ID"
    Public Const RNTL_BT As String = "RNTL_BT"

    Public Const RNTL_ENTRY_ID As String = "RNTL_ENTRY_ID"
    Public Const CNTRCT_RFRNC_NO As String = "CNTRCT_RFRNC_NO"
    Public Const RNTL_RFRNC_NO As String = "RNTL_RFRNC_NO"
    Public Const RNTL_CSTMR_ID As String = "RNTL_CSTMR_ID"
    Public Const RNTL_CSTMR_NAM As String = "RNTL_CSTMR_NAM"
    Public Const RNTL_CSTMR_CD As String = "RNTL_CSTMR_CD"
    Public Const INVCNG_PRTY_ID As String = "INVCNG_PRTY_ID"
    Public Const CNCLD_BY As String = "CNCLD_BY"
    Public Const CNCLD_DT As String = "CNCLD_DT"
    Public Const ADT_RMRKS As String = "ADT_RMRKS"
    Public Const ON_HR_DT As String = "ON_HR_DT"
    Public Const ORGNL_CSTMR_ID As String = "ORGNL_CSTMR_ID"
    Public Const ORGNL_CSTMR_CD As String = "ORGNL_CSTMR_CD"

    'Table Name: V_ACTIVITY_STATUS
    Public Const PRDCT_DSCRPTN_VC As String = "PRDCT_DSCRPTN_VC"
    Public Const INVC_GNRT_BT As String = "INVC_GNRT_BT"
    Public Const GI_RF_NO As String = "GI_RF_NO"
    Public Const INSPCTN_DT As String = "INSPCTN_DT"
    Public Const INSTRCTNS_VC As String = "INSTRCTNS_VC"
    Public Const DPT_NAM As String = "DPT_NAM"
    Public Const FILTER_CODE As String = "FILTER_CODE"
    Public Const CERT_GNRTD_FLG As String = "CERT_GNRTD_FLG"
    Public Const RPR_CMPLTN_DT As String = "RPR_CMPLTN_DT"

    'Table Name: RENTAL_CHARGE
    Public Const RNTL_CHRG_ID As String = "RNTL_CHRG_ID"
    Public Const RNTL_TYP As String = "RNTL_TYP"
    Public Const HNDLNG_OT_NC As String = "HNDLNG_OT_NC"
    Public Const HNDLNG_IN_NC As String = "HNDLNG_IN_NC"
    Public Const ON_HR_SRVY_NC As String = "ON_HR_SRVY_NC"
    Public Const OFF_HR_SRVY_NC As String = "OFF_HR_SRVY_NC"
    Public Const RNTL_PR_DY_NC As String = "RNTL_PR_DY_NC"
    Public Const RNTL_TX_RT_NC As String = "RNTL_TX_RT_NC"
    Public Const RNTL_CNTN_FLG As String = "RNTL_CNTN_FLG"
    Public Const IS_GT_IN_FLG As String = "IS_GT_IN_FLG"
    Public Const DRFT_INVC_NO As String = "DRFT_INVC_NO"
    Public Const FNL_INVC_NO As String = "FNL_INVC_NO"

    'Table Name: CUSTOMER_RENTAL
    Public Const CSTMR_RNTL_ID As String = "CSTMR_RNTL_ID"
    Public Const CNTRCT_STRT_DT As String = "CNTRCT_STRT_DT"
    Public Const CNTRCT_END_DT As String = "CNTRCT_END_DT"
    Public Const MN_TNR_DY As String = "MN_TNR_DY"
    Public Const RNTL_PR_DY As String = "RNTL_PR_DY"
    Public Const HNDLNG_OT As String = "HNDLNG_OT"
    Public Const HNDLNG_IN As String = "HNDLNG_IN"
    Public Const ON_HR_SRVY As String = "ON_HR_SRVY"
    Public Const OFF_HR_SRVY As String = "OFF_HR_SRVY"
    Public Const SPPLR_ID As String = "SPPLR_ID"
    Public Const PO_RFRNC_NO As String = "PO_RFRNC_NO"
    Public Const OTHR_CHRG_NC As String = "OTHR_CHRG_NC"
    Public Const ALLOW_RENTAL As String = "ALLOW_RENTAL"
    Public Const ON_HR_BLLNG_FLG As String = "ON_HR_BLLNG_FLG"
    Public Const OFF_HR_BLLNG_FLG As String = "OFF_HR_BLLNG_FLG"

    'Attachment
    Public Const ATTCHMNT_ID As String = "ATTCHMNT_ID"
    Public Const RPR_ESTMT_NO As String = "RPR_ESTMT_NO"
    Public Const CHK_FLG As String = "CHK_FLG"
    Public Const GI_TRNSTCN_NO As String = "GI_TRNSTCN_NO"
    Public Const ATTCHMNT_PTH As String = "ATTCHMNT_PTH"
    Public Const ACTL_FL_NM As String = "ACTL_FL_NM"
    Public Const COUNT_ATTACH As String = "COUNT_ATTACH"
    Public Const RPR_ESTMT_ID As String = "RPR_ESTMT_ID"
    Public Const CSC_VLDTY As String = "CSC_VLDTY"

    Public Const AGNT_CD As String = "AGNT_CD"
    Public Const INSPCTD_BY As String = "INSPCTD_BY"

#End Region


End Class

#End Region

