#Region "GateinData"
Public Class GateinData

#Region "Declaration Part.."
    'Data Tables..
    Public Const _GATEIN As String = "GATEIN"
    Public Const _GATEIN_RET As String = "GATEIN_RET"
    Public Const _HANDLING_CHARGE As String = "HANDLING_CHARGE"
    Public Const _STORAGE_CHARGE As String = "STORAGE_CHARGE"
    Public Const _V_GATEIN As String = "V_GATEIN"
    Public Const _V_INWARD_PASS As String = "V_INWARD_PASS"
    Public Const _TRACKING As String = "TRACKING"
    Public Const _EQUIPMENT_STATUS As String = "EQUIPMENT_STATUS"
    Public Const _CUSTOMER As String = "CUSTOMER"
    Public Const _GATEIN_DETAIL As String = "GATEIN_DETAIL"
    Public Const _V_GATEIN_DETAIL As String = "V_GATEIN_DETAIL"
    Public Const _EQUIPMENT_INFORMATION As String = "EQUIPMENT_INFORMATION"
    Public Const _V_EQUIPMENT_INFORMATION As String = "V_EQUIPMENT_INFORMATION"
    Public Const _ACTIVITY_STATUS As String = "ACTIVITY_STATUS"
    Public Const _PRE_ADVICE As String = "PRE_ADVICE"
    Public Const _V_CUSTOMER_CHARGE_DETAIL As String = "V_CUSTOMER_CHARGE_DETAIL"
    Public Const _HEATING_CHARGE As String = "HEATING_CHARGE"
    Public Const _MATERIAL As String = "MATERIAL"
    Public Const _MEASURE As String = "MEASURE"
    Public Const _COUNTRY As String = "COUNTRY"
    Public Const _INVOICING_PARTY As String = "INVOICING_PARTY"
    Public Const _UNIT As String = "UNIT"
    Public Const _V_RENTAL_ENTRY As String = "V_RENTAL_ENTRY"
    Public Const _RENTAL_ENTRY As String = "RENTAL_ENTRY"
    Public Const _RENTAL_CHARGE As String = "RENTAL_CHARGE"
    Public Const _CUSTOMER_RENTAL As String = "CUSTOMER_RENTAL"
    Public Const _V_GATEOUT As String = "V_GATEOUT"
    Public Const _V_SUPPLIER_EQUIPMENT_DETAIL As String = "V_SUPPLIER_EQUIPMENT_DETAIL"
    Public Const _EQUIPMENT_INFORMATION_DETAIL As String = "EQUIPMENT_INFORMATION_DETAIL"
    Public Const _EQUIPMENT_INFO_DETAIL As String = "EQUIPMENT_INFO_DETAIL"
    Public Const _CLEANING As String = "CLEANING"
    Public Const _EQUIPMENT_CODE As String = "EQUIPMENT_CODE"
    Public Const _ATTACHMENT As String = "ATTACHMENT"
    Public Const _V_ATTACHMENT As String = "V_ATTACHMENT"
    'Data Columns..
    Public Const EQPMNT_CD_DSCRPTN_VC As String = "EQPMNT_CD_DSCRPTN_VC"
    Public Const _PRODUCT As String = "PRODUCT"
    Public Const _EQUIPMENT_TYPE As String = "EQUIPMENT_TYPE"
    'Data Columns..

    'Table Name: PRODUCT
    Public Const PRDCT_ID As String = "PRDCT_ID"
    Public Const PRDCT_CD As String = "PRDCT_CD"
    Public Const PRDCT_DSCRPTN_VC As String = "PRDCT_DSCRPTN_VC"
    Public Const CHMCL_NM As String = "CHMCL_NM"
    Public Const IMO_CLSS As String = "IMO_CLSS"
    Public Const UN_NO As String = "UN_NO"
    Public Const CLSSFCTN_ID As String = "CLSSFCTN_ID"
    Public Const GRP_CLSSFCTN_ID As String = "GRP_CLSSFCTN_ID"
    Public Const RMRKS_VC As String = "RMRKS_VC"
    Public Const CLNNG_TTL_AMNT_NC As String = "CLNNG_TTL_AMNT_NC"
    Public Const CLNBL_BT As String = "CLNBL_BT"
    Public Const CRTD_BY As String = "CRTD_BY"
    Public Const CRTD_DT As String = "CRTD_DT"
    Public Const MDFD_BY As String = "MDFD_BY"
    Public Const MDFD_DT As String = "MDFD_DT"
    Public Const ACTV_BT As String = "ACTV_BT"
    Public Const DPT_ID As String = "DPT_ID"
    Public Const PRODUCT_CLASSIFICATION As String = "PRODUCT_CLASSIFICATION"
    Public Const GROUP_CLASSIFICATION As String = "GROUP_CLASSIFICATION"

    'Table Name: V_GATEIN
    Public Const CHECKED As String = "CHECKED"
    Public Const GTN_ID As String = "GTN_ID"
    Public Const GTN_CD As String = "GTN_CD"
    Public Const CSTMR_ID As String = "CSTMR_ID"
    Public Const CSTMR_CD As String = "CSTMR_CD"
    Public Const CSTMR_NAM As String = "CSTMR_NAM"
    Public Const EQPMNT_NO As String = "EQPMNT_NO"
    Public Const EQPMNT_TYP_ID As String = "EQPMNT_TYP_ID"
    Public Const EQPMNT_TYP_CD As String = "EQPMNT_TYP_CD"
    Public Const EQPMNT_CD_ID As String = "EQPMNT_CD_ID"
    Public Const EQPMNT_CD_CD As String = "EQPMNT_CD_CD"
    Public Const EQPMNT_STTS_ID As String = "EQPMNT_STTS_ID"
    Public Const EQPMNT_STTS_CD As String = "EQPMNT_STTS_CD"
    Public Const YRD_LCTN As String = "YRD_LCTN"
    Public Const GTN_DT As String = "GTN_DT"
    Public Const GTN_TM As String = "GTN_TM"
    Public Const EIR_NO As String = "EIR_NO"
    Public Const VHCL_NO As String = "VHCL_NO"
    Public Const TRNSPRTR_CD As String = "TRNSPRTR_CD"
    Public Const HTNG_BT As String = "HTNG_BT"
    Public Const GI_TRNSCTN_NO As String = "GI_TRNSCTN_NO"
    Public Const CNCLD_BY As String = "CNCLD_BY"
    Public Const CNCLD_DT As String = "CNCLD_DT"
    Public Const ADT_RMRKS As String = "ADT_RMRKS"
    Public Const EQPMNT_STTS_DSCRPTN_VC As String = "EQPMNT_STTS_DSCRPTN_VC"
    Public Const ALLOW_UPDATE As String = "ALLOW_UPDATE"
    Public Const HTNG_EDIT As String = "HTNG_EDIT"
    Public Const RDL_ATH As String = "RDL_ATH"
    Public Const GRD_ID As String = "GRD_ID"
    Public Const GRD_CD As String = "GRD_CD"
    Public Const CNSGNE As String = "CNSGNE"
    Public Const BLL_ID As String = "BLL_ID"
    Public Const BLL_CD As String = "BLL_CD"
    Public Const AGNT_ID As String = "AGNT_ID"
    Public Const AGNT_CD As String = "AGNT_CD"
    Public Const CSC_VLDTY As String = "CSC_VLDTY"
    'Table Name: GATEIN_DETAIL
    Public Const GTN_DTL_ID As String = "GTN_DTL_ID"
    Public Const MNFCTR_DT As String = "MNFCTR_DT"
    Public Const ACEP_CD As String = "ACEP_CD"
    Public Const MTRL_ID As String = "MTRL_ID"
    Public Const GRSS_WGHT_NC As String = "GRSS_WGHT_NC"
    Public Const TR_WGHT_NC As String = "TR_WGHT_NC"
    Public Const MSR_ID As String = "MSR_ID"
    Public Const UNT_ID As String = "UNT_ID"
    Public Const LST_OH_LOC As String = "LST_OH_LOC"
    Public Const LST_OH_DT As String = "LST_OH_DT"
    Public Const TRCKR_CD As String = "TRCKR_CD"
    Public Const LOD_STTS_CD As String = "LOD_STTS_CD"
    Public Const CNTRY_ID As String = "CNTRY_ID"
    Public Const LIC_STT As String = "LIC_STT"
    Public Const LIC_REG As String = "LIC_REG"
    Public Const LIC_EXPR As String = "LIC_EXPR"
    Public Const NT_1_VC As String = "NT_1_VC"
    Public Const NT_2_VC As String = "NT_2_VC"
    Public Const NT_3_VC As String = "NT_3_VC"
    Public Const NT_4_VC As String = "NT_4_VC"
    Public Const NT_5_VC As String = "NT_5_VC"
    Public Const SL_PRTY_1_ID As String = "SL_PRTY_1_ID"
    Public Const SL_NMBR_1 As String = "SL_NMBR_1"
    Public Const SL_PRTY_2_ID As String = "SL_PRTY_2_ID"
    Public Const SL_NMBR_2 As String = "SL_NMBR_2"
    Public Const SL_PRTY_3_ID As String = "SL_PRTY_3_ID"
    Public Const SL_NMBR_3 As String = "SL_NMBR_3"
    Public Const PRT_FNC_CD As String = "PRT_FNC_CD"
    Public Const PRT_NM As String = "PRT_NM"
    Public Const PRT_NO As String = "PRT_NO"
    Public Const PRT_LC_CD As String = "PRT_LC_CD"
    Public Const VSSL_NM As String = "VSSL_NM"
    Public Const VYG_NO As String = "VYG_NO"
    Public Const VSSL_CD As String = "VSSL_CD"
    Public Const SHPPR_NAM As String = "SHPPR_NAM"
    Public Const RL_ID_VC As String = "RL_ID_VC"
    Public Const RL_RMP_LOC As String = "RL_RMP_LOC"
    Public Const HAZ_MTL_CD As String = "HAZ_MTL_CD"
    Public Const HAZ_MATL_DSC As String = "HAZ_MATL_DSC"
    Public Const MORE_INFO_BIT As String = "MORE_INFO_BIT"
    Public Const INVCNG_PRTY_CD As String = "INVCNG_PRTY_CD"
    Public Const PRTY_ID As String = "PRTY_ID"
    'Table Name: GATEIN_RET
    Public Const GI_SNO As String = "GI_SNO"
    Public Const GI_TRANSMISSION_NO As String = "GI_TRANSMISSION_NO"
    Public Const GI_COMPLETE As String = "GI_COMPLETE"
    Public Const GI_SENT_EIR As String = "GI_SENT_EIR"
    Public Const GI_SENT_DATE As String = "GI_SENT_DATE"
    Public Const GI_REC_EIR As String = "GI_REC_EIR"
    Public Const GI_REC_DATE As String = "GI_REC_DATE"
    Public Const GI_REC_ADDR As String = "GI_REC_ADDR"
    Public Const GI_REC_TYPE As String = "GI_REC_TYPE"
    Public Const GI_EXPORTED As String = "GI_EXPORTED"
    Public Const GI_EXPOR_DATE As String = "GI_EXPOR_DATE"
    Public Const GI_IMPORTED As String = "GI_IMPORTED"
    Public Const GI_IMPOR_DATE As String = "GI_IMPOR_DATE"
    Public Const GI_TRNSXN As String = "GI_TRNSXN"
    Public Const GI_ADVICE As String = "GI_ADVICE"
    Public Const GI_UNIT_NBR As String = "GI_UNIT_NBR"
    Public Const GI_EQUIP_TYPE As String = "GI_EQUIP_TYPE"
    Public Const GI_EQUIP_DESC As String = "GI_EQUIP_DESC"
    Public Const GI_EQUIP_CODE As String = "GI_EQUIP_CODE"
    Public Const GI_CONDITION As String = "GI_CONDITION"
    Public Const GI_COMP_ID_A As String = "GI_COMP_ID_A"
    Public Const GI_COMP_ID_N As String = "GI_COMP_ID_N"
    Public Const GI_COMP_ID_C As String = "GI_COMP_ID_C"
    Public Const GI_COMP_TYPE As String = "GI_COMP_TYPE"
    Public Const GI_COMP_DESC As String = "GI_COMP_DESC"
    Public Const GI_COMP_CODE As String = "GI_COMP_CODE"
    Public Const GI_EIR_DATE As String = "GI_EIR_DATE"
    Public Const GI_EIR_TIME As String = "GI_EIR_TIME"
    Public Const GI_REFERENCE As String = "GI_REFERENCE"
    Public Const GI_MANU_DATE As String = "GI_MANU_DATE"
    Public Const GI_MATERIAL As String = "GI_MATERIAL"
    Public Const GI_WEIGHT As String = "GI_WEIGHT"
    Public Const GI_MEASURE As String = "GI_MEASURE"
    Public Const GI_UNITS As String = "GI_UNITS"
    Public Const GI_CSC_REEXAM As String = "GI_CSC_REEXAM"
    Public Const GI_COUNTRY As String = "GI_COUNTRY"
    Public Const GI_LIC_STATE As String = "GI_LIC_STATE"
    Public Const GI_LIC_REG As String = "GI_LIC_REG"
    Public Const GI_LIC_EXPIRE As String = "GI_LIC_EXPIRE"
    Public Const GI_LSR_OWNER As String = "GI_LSR_OWNER"
    Public Const GI_SEND_EDI_1 As String = "GI_SEND_EDI_1"
    Public Const GI_SSL_LSE As String = "GI_SSL_LSE"
    Public Const GI_SEND_EDI_2 As String = "GI_SEND_EDI_2"
    Public Const GI_HAULIER As String = "GI_HAULIER"
    Public Const GI_SEND_EDI_3 As String = "GI_SEND_EDI_3"
    Public Const GI_DPT_TRM As String = "GI_DPT_TRM"
    Public Const GI_SEND_EDI_4 As String = "GI_SEND_EDI_4"
    Public Const GI_OTHERS_1 As String = "GI_OTHERS_1"
    Public Const GI_OTHERS_2 As String = "GI_OTHERS_2"
    Public Const GI_OTHERS_3 As String = "GI_OTHERS_3"
    Public Const GI_OTHERS_4 As String = "GI_OTHERS_4"
    Public Const GI_NOTE_1 As String = "GI_NOTE_1"
    Public Const GI_NOTE_2 As String = "GI_NOTE_2"
    Public Const GI_LOAD As String = "GI_LOAD"
    Public Const GI_FHWA As String = "GI_FHWA"
    Public Const GI_LAST_OH_LOC As String = "GI_LAST_OH_LOC"
    Public Const GI_LAST_OH_DATE As String = "GI_LAST_OH_DATE"
    Public Const GI_SENDER As String = "GI_SENDER"
    Public Const GI_ATTENTION As String = "GI_ATTENTION"
    Public Const GI_REVISION As String = "GI_REVISION"
    Public Const GI_SEND_EDI_5 As String = "GI_SEND_EDI_5"
    Public Const GI_SEND_EDI_6 As String = "GI_SEND_EDI_6"
    Public Const GI_SEND_EDI_7 As String = "GI_SEND_EDI_7"
    Public Const GI_SEND_EDI_8 As String = "GI_SEND_EDI_8"
    Public Const GI_SEAL_PARTY_1 As String = "GI_SEAL_PARTY_1"
    Public Const GI_SEAL_NUMBER_1 As String = "GI_SEAL_NUMBER_1"
    Public Const GI_SEAL_PARTY_2 As String = "GI_SEAL_PARTY_2"
    Public Const GI_SEAL_NUMBER_2 As String = "GI_SEAL_NUMBER_2"
    Public Const GI_SEAL_PARTY_3 As String = "GI_SEAL_PARTY_3"
    Public Const GI_SEAL_NUMBER_3 As String = "GI_SEAL_NUMBER_3"
    Public Const GI_SEAL_PARTY_4 As String = "GI_SEAL_PARTY_4"
    Public Const GI_SEAL_NUMBER_4 As String = "GI_SEAL_NUMBER_4"
    Public Const GI_PORT_FUNC_CODE As String = "GI_PORT_FUNC_CODE"
    Public Const GI_PORT_NAME As String = "GI_PORT_NAME"
    Public Const GI_VESSEL_NAME As String = "GI_VESSEL_NAME"
    Public Const GI_VOYAGE_NUM As String = "GI_VOYAGE_NUM"
    Public Const GI_HAZ_MAT_CODE As String = "GI_HAZ_MAT_CODE"
    Public Const GI_HAZ_MAT_DESC As String = "GI_HAZ_MAT_DESC"
    Public Const GI_NOTE_3 As String = "GI_NOTE_3"
    Public Const GI_NOTE_4 As String = "GI_NOTE_4"
    Public Const GI_NOTE_5 As String = "GI_NOTE_5"
    Public Const GI_COMP_ID_A_2 As String = "GI_COMP_ID_A_2"
    Public Const GI_COMP_ID_N_2 As String = "GI_COMP_ID_N_2"
    Public Const GI_COMP_ID_C_2 As String = "GI_COMP_ID_C_2"
    Public Const GI_COMP_TYPE_2 As String = "GI_COMP_TYPE_2"
    Public Const GI_COMP_CODE_2 As String = "GI_COMP_CODE_2"
    Public Const GI_COMP_DESC_2 As String = "GI_COMP_DESC_2"
    Public Const GI_SHIPPER As String = "GI_SHIPPER"
    Public Const GI_DRAY_ORDER As String = "GI_DRAY_ORDER"
    Public Const GI_RAIL_ID As String = "GI_RAIL_ID"
    Public Const GI_RAIL_RAMP As String = "GI_RAIL_RAMP"
    Public Const GI_VESSEL_CODE As String = "GI_VESSEL_CODE"
    Public Const GI_WGHT_CERT_1 As String = "GI_WGHT_CERT_1"
    Public Const GI_WGHT_CERT_2 As String = "GI_WGHT_CERT_2"
    Public Const GI_WGHT_CERT_3 As String = "GI_WGHT_CERT_3"
    Public Const GI_SEA_RAIL As String = "GI_SEA_RAIL"
    Public Const GI_LOC_IDENT As String = "GI_LOC_IDENT"
    Public Const GI_PORT_LOC_QUAL As String = "GI_PORT_LOC_QUAL"
    Public Const GI_STATUS As String = "GI_STATUS"
    Public Const GI_PICK_DATE As String = "GI_PICK_DATE"
    Public Const GI_ESTSTATUS As String = "GI_ESTSTATUS"
    Public Const GI_ERRSTATUS As String = "GI_ERRSTATUS"
    Public Const GI_USERNAME As String = "GI_USERNAME"
    Public Const GI_LIVE_STATUS As String = "GI_LIVE_STATUS"
    Public Const GI_ISACTIVE As String = "GI_ISACTIVE"
    Public Const GI_YARD_LOC As String = "GI_YARD_LOC"
    Public Const GI_MODE_PAYMENT As String = "GI_MODE_PAYMENT"
    Public Const GI_BILLING_TYPE As String = "GI_BILLING_TYPE"
    Public Const GI_RESERVE_BKG As String = "GI_RESERVE_BKG"
    Public Const GI_RCESTSTATUS As String = "GI_RCESTSTATUS"
    Public Const OP_SNO As String = "OP_SNO"
    Public Const OP_STATUS As String = "OP_STATUS"

    'Table Name: HANDLING_CHARGE
    Public Const HNDLNG_CHRG_ID As String = "HNDLNG_CHRG_ID"
    Public Const EQPMNT_SZ_ID As String = "EQPMNT_SZ_ID"
    Public Const CST_TYP As String = "CST_TYP"
    Public Const RFRNC_EIR_NO_1 As String = "RFRNC_EIR_NO_1"
    Public Const RFRNC_EIR_NO_2 As String = "RFRNC_EIR_NO_2"
    Public Const FRM_BLLNG_DT As String = "FRM_BLLNG_DT"
    Public Const TO_BLLNG_DT As String = "TO_BLLNG_DT"
    Public Const FR_DYS As String = "FR_DYS"
    Public Const NO_OF_DYS As String = "NO_OF_DYS"
    Public Const HNDLNG_CST_NC As String = "HNDLNG_CST_NC"
    Public Const HNDLNG_TX_RT_NC As String = "HNDLNG_TX_RT_NC"
    Public Const TTL_CSTS_NC As String = "TTL_CSTS_NC"
    Public Const BLLNG_FLG As String = "BLLNG_FLG"
    Public Const IS_GT_OT_FLG As String = "IS_GT_OT_FLG"
    Public Const BLLNG_TYP_CD As String = "BLLNG_TYP_CD"

    'Table Name: STORAGE_CHARGE
    Public Const STRG_CHRG_ID As String = "STRG_CHRG_ID"
    Public Const STRG_CST_NC As String = "STRG_CST_NC"
    Public Const STRG_TX_RT_NC As String = "STRG_TX_RT_NC"
    Public Const STRG_CNTN_FLG As String = "STRG_CNTN_FLG"
    Public Const IS_LT_FLG As String = "IS_LT_FLG"
    Public Const BLLNG_TLL_DT As String = "BLLNG_TLL_DT"
    Public Const YARD_LCTN As String = "YARD_LCTN"
    Public Const MODE_PYMNT As String = "MODE_PYMNT"
    Public Const HNDLNG_CHRG_NC As String = "HNDLNG_CHRG_NC"
    Public Const WSHNG_CHRG_NC As String = "WSHNG_CHRG_NC"

    ''Table Name: V_GATEIN    
    Public Const MTRL_CD As String = "MTRL_CD"
    Public Const MSR_CD As String = "MSR_CD"
    Public Const UNT_CD As String = "UNT_CD"
    Public Const CNTRY_CD As String = "CNTRY_CD"
    Public Const SL_PRTY_1_CD As String = "SL_PRTY_1_CD"
    Public Const SL_PRTY_2_CD As String = "SL_PRTY_2_CD"
    Public Const SL_PRTY_3_CD As String = "SL_PRTY_3_CD"
    Public Const SL_PRTY_4_CD As String = "SL_PRTY_4_CD"
    Public Const GTOT_BT As String = "GTOT_BT"
    Public Const GTN_BIN As String = "GTN_BIN"
    Public Const ACTVTY_DT As String = "ACTVTY_DT"
    Public Const BLLNG_TYP As String = "BLLNG_TYP"

    'Table Name: TRACKING
    Public Const TRCKNG_ID As String = "TRCKNG_ID"
    Public Const ACTVTY_NAM As String = "ACTVTY_NAM"
    Public Const ACTVTY_NO As String = "ACTVTY_NO"
    Public Const ACTVTY_RMRKS As String = "ACTVTY_RMRKS"
    Public Const INVCNG_PRTY_ID As String = "INVCNG_PRTY_ID"
    Public Const HNDLNG_IN_CHRG_NC As String = "HNDLNG_IN_CHRG_NC"
    Public Const HNDLNG_OUT_CHRG_NC As String = "HNDLNG_OUT_CHRG_NC"
    Public Const STRG_CHRGS_PR_DY_NC As String = "STRG_CHRGS_PR_DY_NC"
    Public Const RFRNC_NO As String = "RFRNC_NO"

    'Table Name: EQUIPMENT_INFORMATION
    Public Const EQPMNT_INFRMTN_ID As String = "EQPMNT_INFRMTN_ID"
    Public Const CPCTY_NC As String = "CPCTY_NC"
    Public Const LST_SRVYR_NM As String = "LST_SRVYR_NM"
    Public Const LST_TST_DT As String = "LST_TST_DT"
    Public Const LST_TST_TYP_ID As String = "LST_TST_TYP_ID"
    Public Const LST_TST_TYP_CD As String = "LST_TST_TYP_CD"
    Public Const NXT_TST_DT As String = "NXT_TST_DT"
    Public Const NXT_TST_TYP_ID As String = "NXT_TST_TYP_ID"
    Public Const NXT_TST_TYP_CD As String = "NXT_TST_TYP_CD"
    Public Const EQPMNT_INFRMTN_RMRKS_VC As String = "EQPMNT_INFRMTN_RMRKS_VC"

    'Table Name: Equipment_Information_Detail
    Public Const EQPMNT_INFRMTN_DTL_ID As String = "EQPMNT_INFRMTN_DTL_ID"
    Public Const ATTCHMNT_PTH As String = "ATTCHMNT_PTH"
    Public Const ACTL_FL_NM As String = "ACTL_FL_NM"
    Public Const COUNT_ATTACH As String = "COUNT_ATTACH"
    Public Const HAS_CHANGE As String = "HAS_CHANGE"
   
    'Table Name: ACTIVITY_STATUS
    Public Const ACTVTY_STTS_ID As String = "ACTVTY_STTS_ID"
    Public Const GTOT_DT As String = "GTOT_DT"
    Public Const CLNNG_DT As String = "CLNNG_DT"
    Public Const ACTVTY_ID As String = "ACTVTY_ID"
    Public Const RMRKS_VCR As String = "RMRKS_VCR"
    Public Const GI_RF_NO As String = "GI_RF_NO"
    'Table:PRE_ADVICE
    Public Const PR_ADVC_ID As String = "PR_ADVC_ID"
    Public Const EQPMNT_SZ_CD As String = "EQPMNT_SZ_CD"
    Public Const CLNNG_RFRNC_NO As String = "CLNNG_RFRNC_NO"
    Public Const PR_ADVC_CD As String = "PR_ADVC_CD"
    Public Const PR_ADVC_BT As String = "PR_ADVC_BT"

    'Table Name: CUSTOMER_CHARGE_DETAIL
    Public Const CSTMR_CHRG_DTL_ID As String = "CSTMR_CHRG_DTL_ID"
    Public Const INVC_GNRT_BT As String = "INVC_GNRT_BT"
    Public Const RNTL_BT As String = "RNTL_BT"

    'Table Name: V_RENTAL_ENTRY
    Public Const RNTL_ENTRY_ID As String = "RNTL_ENTRY_ID"
    Public Const CNTRCT_RFRNC_NO As String = "CNTRCT_RFRNC_NO"
    Public Const PO_RFRNC_NO As String = "PO_RFRNC_NO"
    Public Const RNTL_PR_DY As String = "RNTL_PR_DY"
    Public Const ON_HR_DT As String = "ON_HR_DT"
    Public Const HNDLNG_OT_NC As String = "HNDLNG_OT_NC"
    Public Const ON_HR_SRVY_NC As String = "ON_HR_SRVY_NC"
    Public Const OFF_HR_DT As String = "OFF_HR_DT"
    Public Const HNDLNG_IN_NC As String = "HNDLNG_IN_NC"
    Public Const OFF_HR_SRVY_NC As String = "OFF_HR_SRVY_NC"
    Public Const OTHR_CHRG_NC As String = "OTHR_CHRG_NC"
    Public Const RNTL_RFRNC_NO As String = "RNTL_RFRNC_NO"
    Public Const GTN_BT As String = "GTN_BT"
    Public Const RNTL_CSTMR_ID As String = "RNTL_CSTMR_ID"

    'Table Name: RENTAL_CHARGE
    Public Const RNTL_CHRG_ID As String = "RNTL_CHRG_ID"
    Public Const RNTL_TYP As String = "RNTL_TYP"
    Public Const RNTL_PR_DY_NC As String = "RNTL_PR_DY_NC"
    Public Const RNTL_TX_RT_NC As String = "RNTL_TX_RT_NC"
    Public Const RNTL_CNTN_FLG As String = "RNTL_CNTN_FLG"
    Public Const IS_GT_IN_FLG As String = "IS_GT_IN_FLG"
    Public Const DRFT_INVC_NO As String = "DRFT_INVC_NO"
    Public Const FNL_INVC_NO As String = "FNL_INVC_NO"
    Public Const OFF_HR_SRVY As String = "OFF_HR_SRVY"
    Public Const ON_HR_SRVY As String = "ON_HR_SRVY"
    Public Const HNDLNG_IN As String = "HNDLNG_IN"
    Public Const HNDLNG_OT As String = "HNDLNG_OT"
    Public Const ALLOW_RENTAL As String = "ALLOW_RENTAL"
    Public Const IS_GTOT_BT As String = "IS_GTOT_BT"

    Public Const LST_CLNNG_DT As String = "LST_CLNNG_DT"

    'Attachment
    Public Const ATTCHMNT_ID As String = "ATTCHMNT_ID"
    Public Const RPR_ESTMT_NO As String = "RPR_ESTMT_NO"
    Public Const CHK_FLG As String = "CHK_FLG"
    Public Const GI_TRNSTCN_NO As String = "GI_TRNSTCN_NO"
    Public Const RPR_ESTMT_ID As String = "RPR_ESTMT_ID"

#End Region

End Class

#End Region
