#Region "ScheduleData"

Public Class ScheduleData

    Public Const _V_REPAIR_ESTIMATE As String = "V_REPAIR_ESTIMATE"
    Public Const _V_ACTIVITY_STATUS As String = "V_ACTIVITY_STATUS"
    Public Const _REPAIR_ESTIMATE As String = "REPAIR_ESTIMATE"
    Public Const _ACTIVITY_STATUS As String = "ACTIVITY_STATUS"
    Public Const _ENUM As String = "enum"
    Public Const _V_SCHEDULE_USER_RIGHTS As String = "V_SCHEDULE_USER_RIGHTS"

    'Data Columns..
    'Table Name: CLEANING
    Public Const PRDCT_DSCRPTN_VC As String = "PRDCT_DSCRPTN_VC"
    Public Const CLNNG_ID As String = "CLNNG_ID"
    Public Const CLNNG_CD As String = "CLNNG_CD"
    Public Const CSTMR_ID As String = "CSTMR_ID"
    Public Const EQPMNT_NO As String = "EQPMNT_NO"
    Public Const CLNNG_CERT_NO As String = "CLNNG_CERT_NO"
    Public Const PRDCT_ID As String = "PRDCT_ID"
    Public Const CHMCL_NM As String = "CHMCL_NM"
    Public Const CLNNG_RT As String = "CLNNG_RT"
    Public Const ORGNL_CLNNG_DT As String = "ORGNL_CLNNG_DT"
    Public Const LST_CLNNG_DT As String = "LST_CLNNG_DT"
    Public Const ORGNL_INSPCTD_DT As String = "ORGNL_INSPCTD_DT"
    Public Const LST_INSPCTD_DT As String = "LST_INSPCTD_DT"
    Public Const EQPMNT_STTS_ID As String = "EQPMNT_STTS_ID"
    Public Const CLND_FR_VCR As String = "CLND_FR_VCR"
    Public Const LCTN_OF_CLNG As String = "LCTN_OF_CLNG"
    Public Const EQPMNT_CLNNG_STTS_1 As String = "EQPMNT_CLNNG_STTS_1"
    Public Const EQPMNT_CLNNG_STTS_2 As String = "EQPMNT_CLNNG_STTS_2"
    Public Const EQPMNT_CNDTN_ID As String = "EQPMNT_CNDTN_ID"
    Public Const VLV_FTTNG_CNDTN As String = "VLV_FTTNG_CNDTN"
    Public Const MN_LID_SL_NO As String = "MN_LID_SL_NO"
    Public Const TP_SL_NO As String = "TP_SL_NO"
    Public Const BTTM_SL_NO As String = "BTTM_SL_NO"
    Public Const INVCNG_PRTY_ID As String = "INVCNG_PRTY_ID"
    Public Const CSTMR_RFRNC_NO As String = "CSTMR_RFRNC_NO"
    Public Const CLNNG_RFRNC_NO As String = "CLNNG_RFRNC_NO"
    Public Const RMRKS_VC As String = "RMRKS_VC"
    Public Const DPT_ID As String = "DPT_ID"
    Public Const GI_TRNSCTN_NO As String = "GI_TRNSCTN_NO"
    Public Const CRTD_BY As String = "CRTD_BY"
    Public Const CRTD_DT As String = "CRTD_DT"
    Public Const MDFD_BY As String = "MDFD_BY"
    Public Const MDFD_DT As String = "MDFD_DT"
    Public Const CERT_GNRTD_FLG As String = "CERT_GNRTD_FLG"
    Public Const IS_CHNG_OF_STTS As String = "IS_CHNG_OF_STTS"
    Public Const ADDTNL_CLNNG_BT As String = "ADDTNL_CLNNG_BT"


    'Table Name: REPAIR_ESTIMATE
    Public Const RPR_ESTMT_ID As String = "RPR_ESTMT_ID"
    Public Const RPR_ESTMT_DT As String = "RPR_ESTMT_DT"
    Public Const SRVYR_NAM As String = "SRVYR_NAM"
    Public Const WGHT_NC As String = "WGHT_NC"
    Public Const ESTMTN_TTL_NC As String = "ESTMTN_TTL_NC"
    Public Const EIR_NO As String = "EIR_NO"
    Public Const APPRVL_AMNT_NC As String = "APPRVL_AMNT_NC"
    Public Const ORGNL_ESTMN_DT As String = "ORGNL_ESTMN_DT"
    Public Const TTL_LBR_CST_NC As String = "TTL_LBR_CST_NC"
    Public Const TR_WGHT_NC As String = "TR_WGHT_NC"
    Public Const GRSS_WGHT_NC As String = "GRSS_WGHT_NC"
    Public Const LBR_RT_NC As String = "LBR_RT_NC"
    Public Const CSTMR_ESTMTN_TTL_NC As String = "CSTMR_ESTMTN_TTL_NC"
    Public Const CSTMR_APPRVL_AMNT_NC As String = "CSTMR_APPRVL_AMNT_NC"
    Public Const OWNR_APPRVL_DT As String = "OWNR_APPRVL_DT"
    Public Const OWNR_APPRVL_AMNT_NC As String = "OWNR_APPRVL_AMNT_NC"
    Public Const RPR_CMPLTN_DT As String = "RPR_CMPLTN_DT"
    Public Const RPR_CMPLTN_RMRKS As String = "RPR_CMPLTN_RMRKS"
    Public Const SRVYR_NM As String = "SRVYR_NM"
    Public Const SRVY_DT As String = "SRVY_DT"
    Public Const ESTMT_CRTD_BY As String = "ESTMT_CRTD_BY"
    Public Const PRTY_APPRVL_RF As String = "PRTY_APPRVL_RF"
    Public Const SCHDL_DT As String = "SCHDL_DT"
    Public Const ACTVTY_STTS_ID As String = "ACTVTY_STTS_ID"
    Public Const CHECKED As String = "CHECKED"

End Class
#End Region

